In [1]:
# colab <-> gpu 연동
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

2026-03-24 09:08:18.377416: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-24 09:08:19.252213: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-24 09:08:20.563224: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

2026-03-24 09:08:22.456084: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-03-24 09:08:22.704621: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2026-03-24 09:08:22.704671: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.

# GPT 사용해보기

In [2]:
pip install openai

Collecting openai
  Downloading openai-2.29.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in ./tf-env/lib/python3.12/site-packages (from openai) (4.12.1)
Collecting distro<2,>=1.7.0 (from openai)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai)
  Downloading jiter-0.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Collecting pydantic<3,>=1.9.0 (from openai)
  Downloading pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 10.5 MB/s eta 0:00:00
Collecting sniffio (from openai)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>4 in ./tf-env/lib/python3.12/site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in ./tf-env/lib/python3.12/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in ./tf-env/lib/python3.12/site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./tf-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=1.9.0->openai)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3,>=1.9.0->openai)
  Downloading pydantic_core-2.41.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=1.9.0->openai)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Downloading openai-2.29.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 32.3 MB/s eta 0:00:00
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading jiter-0.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (360 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.7/360.7 kB 38.1 MB/s eta 0:00:00
Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 463.6/463.6 kB 44.0 MB/s eta 0:00:00
Downloading pydantic_core-2.41.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 38.4 MB/s eta 0:00:00
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: typing-inspection, sniffio, pydantic-core, jiter, distro, annotated-types, pydantic, openai
Successfully installed annotated-types-0.7.0 distro-1.9.0 jiter-0.13.0 openai-2.29.0 pydantic-2.12.5 pydantic-core-2.41.5 sniffio-1.3.1 typing-inspection-0.4.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import openai
client = openai.OpenAI(api_key="")

답변받기

In [12]:
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "user", "content": "2020년 월드시리즈에서는 누가 우승했어?"}
    ]
)

# 답변을 받는 방법
print(response.choices[0].message.content)

2020년 월드시리즈 우승팀은 **로스앤젤레스 다저스(Los Angeles Dodgers)** 입니다.

다저스는 **탬파베이 레이스**를 상대로 **4승 2패**로 이겼어요.
또한 **무키 베츠**, **코리 시거** 등이 활약했고, **코리 시거가 월드시리즈 MVP**를 받았습니다.

In [41]:

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "system", "content": "너는 친절하게 답변해주는 비서야. 답변은 반말로 해줘"},
        {"role": "user", "content": "2020년 월드시리즈에서는 누가 우승했어?"}
    ]
)

# 답변을 받는 방법
print(response.choices[0].message.content)

2020년 월드시리즈 우승팀은 **로스앤젤레스 다저스(Los Angeles Dodgers)**야.
탬파베이 레이스를 꺾고 우승했어.

In [42]:

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "user", "content": "2002년 월드컵에서 가장 화제가 되었던 나라는 어디야?"},
        {"role": "assistant", "content": "바로 예상을 뚫고 4강 진출 신화를 일으킨 한국입니다."},
        {"role": "user", "content": "그 나라가 화제가 되었던 이유를 자세하게 설명해줘"}
    ]
)
# 답변받는 방법
print(response.choices[0].message.content)

2002년 FIFA 월드컵에서 **대한민국**이 가장 큰 화제가 된 이유는, 단순히 “개최국이 잘했다” 수준이 아니라 **세계 축구사에서 보기 드문 충격적인 성과와 상징성**을 동시에 보여줬기 때문입니다. 핵심 이유를 자세히 정리하면 아래와 같습니다.

---

## 1. 아무도 예상하지 못한 4강 진출
당시 한국은 월드컵에서 강호로 분류되는 팀이 아니었습니다.
2002년 이전까지 한국은 월드컵 본선에 여러 차례 출전했지만, **한 번도 16강에 올라간 적이 없었습니다.** 그래서 대회 시작 전만 해도 많은 해외 언론과 팬들은 한국이 조별리그를 통과하기 어렵다고 봤습니다.

그런데 한국은:

- **조별리그 통과**
- **16강 진출**
- **8강 진출**
- 결국 **4강 진출**

까지 해냈습니다.

이건 당시 세계적으로 엄청난 이변이었고, 아시아 축구 전체의 위상을 끌어올린 사건으로 평가받았습니다.

---

## 2. 강팀들을 연달아 꺾은 임팩트
한국이 화제가 된 더 큰 이유는 단순히 성적만이 아니라, **상대가 매우 강했다는 점**입니다.

### 조별리그
- **폴란드전 승리 (2:0)**
  한국의 월드컵 본선 첫 승이라서 역사적인 의미가 컸습니다.
- **미국전 무승부 (1:1)**
  만만치 않은 팀을 상대로 승점을 얻었습니다.
- **포르투갈전 승리 (1:0)**
  당시 포르투갈은 세계적인 스타 선수들이 있던 강팀이었는데, 한국이 이겨서 16강에 올랐습니다.

### 토너먼트
- **16강: 이탈리아전 승리 (2:1, 연장전)**
  당시 이탈리아는 전통의 축구 강국이었고, 한국이 이긴 것은 전 세계에 큰 충격을 줬습니다.
- **8강: 스페인전 승리 (승부차기)**
  스페인도 강팀이었기 때문에, 한국의 4강 진출은 “기적”처럼 받아들여졌습니다.

즉, 한국은 약한 팀들만 상대한 것이 아니라 **유럽의 전통 강호들을 상대로 결과를 냈기 때문에** 더 화제가 됐습니다.

---

## 3. 아시아 국가 최초의 월드컵 4강
한국은 2002년 대회에서 **아시아 국가 최초로 월드컵 4강**에 올랐습니다.
이 기록은 단지 한국 축구만의 성과가 아니라, 당시에는 “아시아 팀은 월드컵에서 한계가 있다”는 인식을 뒤흔드는 사건이었습니다.

그래서 한국의 성과는 한국 내부뿐 아니라:

- 일본
- 중국
- 중동 국가들
- 동남아 국가들

까지 포함한 아시아 축구 팬들에게도 큰 자극이 됐습니다.

---

## 4. 홈 개최국의 엄청난 응원 열기
2002년 월드컵은 **한국과 일본이 공동 개최**했는데, 특히 한국은 거리 응원 문화로 세계적인 관심을 받았습니다.

### 붉은악마와 거리응원
- 수많은 시민들이 **빨간 티셔츠**를 입고 거리로 나왔고,
- 서울 광화문, 시청 앞, 전국 주요 도시에서 대규모 응원이 펼쳐졌습니다.
- 응원 인파가 수십만, 어떤 날은 수백만 명 규모로 모였습니다.

이 장면은 전 세계 방송을 통해 소개되며, 한국 사회의 응집력과 축제 분위기를 상징하는 장면이 됐습니다.

당시 외신들은 한국의 응원 문화를:
- 질서정연하면서도 열정적이고
- 집단적인 에너지가 강하며
- 국가적 축제의 모습이 인상적이었다고 평가했습니다.

즉, 화제가 된 건 경기 결과만이 아니라 **국민 전체가 하나의 거대한 축제에 참여하는 모습**이었습니다.

---

## 5. 히딩크 감독 신드롬
당시 한국 대표팀 감독은 **거스 히딩크**였습니다.
그는 네덜란드 출신 감독으로, 체력, 조직력, 압박, 정신력을 강조하는 방식으로 팀을 완전히 바꿔 놓았습니다.

### 왜 히딩크가 화제가 됐나?
- 한국 축구의 체질을 바꾼 인물로 평가받음
- 스타 개인보다는 팀 전술과 조직력을 강조
- 세계 강호를 상대로도 주눅 들지 않는 경기 운영
- 선수 기용과 훈련 방식이 혁신적이었다는 평가

한국이 계속 승리하자 히딩크는 거의 국민적 영웅이 되었고,
“히딩크 리더십”은 스포츠를 넘어 사회 전반에서도 자주 언급될 정도였습니다.

---

## 6. 국민적 자부심과 사회적 분위기
2002년 한국의 4강 신화는 단순한 스포츠 성과를 넘어서, 한국 사회 전체에 큰 자신감을 주었습니다.

당시 한국은:
- 1997년 외환위기(IMF) 이후 사회적으로 회복 중이었고,
- 국제무대에서 한국의 존재감을 더 크게 보여주고 싶어하던 시기였습니다.

이런 상황에서 월드컵 4강은 많은 국민들에게:
- “우리도 세계 무대에서 할 수 있다”
- “한국이 선진 축구 강국들을 이길 수 있다”
- “국민이 함께 모이면 큰 일을 해낼 수 있다”

라는 상징적인 의미로 받아들여졌습니다.

그래서 2002년 월드컵의 한국은 축구팀 이상의 의미를 가졌습니다.

---

## 7. 동시에 판정 논란도 컸음
한국이 화제가 된 이유 중 하나는 긍정적인 면만이 아니라, **논란도 매우 컸기 때문**입니다.

특히:
- **이탈리아전**
- **스페인전**

에서는 심판 판정에 대한 국제적 논쟁이 크게 일어났습니다.

예를 들어:
- 상대 팀의 골 취소
- 파울 판정
- 퇴장 판정

등이 논란이 되었고, 일부 해외 팬들과 언론은 한국의 승리에 대해 의문을 제기했습니다.

그래서 2002년 한국은
**“기적의 팀”으로도 기억되지만, 동시에 가장 논쟁적이었던 팀 중 하나**로도 남았습니다.

이 점 때문에 한국은 대회 내내 세계적으로 엄청나게 많이 언급되었습니다.

---

## 8. 스타 선수들의 등장
이 대회를 통해 한국 선수들도 세계적으로 이름을 알렸습니다.

대표적으로:
- **안정환**: 이탈리아전 연장 골든골
- **박지성**: 포르투갈전 결승골, 뛰어난 활동량
- **이운재**: 승부차기 선방
- **홍명보**: 팀의 중심이자 상징적인 주장 역할
- **유상철, 설기현, 이영표, 송종국** 등도 큰 주목을 받음

특히 박지성은 이 대회를 계기로 세계 무대에서 더 큰 주목을 받았고, 이후 유럽 진출과 커리어 확장의 발판을 마련했습니다.

---

## 정리하면
2002년 월드컵에서 대한민국이 가장 화제가 된 이유는 다음이 한꺼번에 겹쳤기 때문입니다.

1. **월드컵 첫 16강을 넘어 4강까지 간 충격적인 성적**
2. **포르투갈, 이탈리아, 스페인 같은 강팀을 상대로 한 이변**
3. **아시아 국가 최초의 월드컵 4강이라는 역사성**
4. **붉은악마와 거리응원으로 상징되는 엄청난 국민적 열기**
5. **히딩크 감독과 대표팀의 드라마 같은 스토리**
6. **국민적 자부심과 시대적 상징성**
7. **판정 논란까지 겹치며 전 세계적 관심 집중**

한마디로 말하면,
**한국은 2002년 월드컵에서 “성적, 감동, 열기, 논란”을 모두 가진 가장 강렬한 팀이었기 때문에 가장 큰 화제가 되었습니다.**

원하시면 다음 답변에서
**“2002년 한국의 경기별 내용(폴란드전~독일전까지)”**도 차례대로 자세히 설명해드릴게요.

In [43]:
# 이전 대화를 포함 한  답변 받기
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role": "user",
            "content": "2002년   월 드 컵 에 서   가 장   화 제 가   되 었 던   나 라 는 어 디 야 ?"
        },
        {
            "role": "assistant",
            "content": "바 로   예 상 을   뚫 고  4강   진 출   신 화 를   일 으 킨 한 국 입 니 다 ."
        },
        {
            "role": "user",
            "content": "그   나 라 가   화 제 가   되 었 던   이 유 를   자 세 하 게   설 명 해 줘 "
        }
    ]
)

print(response.choices[0].message.content)

2002년 월드컵에서 한국이 가장 큰 화제가 된 이유는 단순히 “잘했다” 수준이 아니라, 여러 상징적인 요소가 한꺼번에 겹쳤기 때문입니다.

1. 사상 최초의 4강 진출
한국은 당시까지 월드컵에서 두드러진 성적을 내지 못했던 팀이었는데, 2002년 대회에서 4강까지 올라가는 엄청난 이변을 만들었습니다.
특히 이탈리아, 스페인 같은 강팀들을 꺾고 올라간 과정이 전 세계 축구 팬들에게 큰 충격을 주었습니다.

2. 개최국으로서의 극적인 스토리
2002년 월드컵은 한국과 일본이 공동 개최한 대회였습니다.
그중에서도 한국은 개최국의 이점을 잘 살리면서, 홈 관중의 열광적인 응원 속에서 기대 이상의 경기력을 보여 주었습니다.
개최국이 대회 분위기를 주도하며 성적까지 내자 국제적으로 더 주목받았습니다.

3. 붉은악마와 거리응원 문화
한국의 응원 문화는 세계적으로도 큰 인상을 남겼습니다.
수많은 사람들이 빨간 티셔츠를 입고 광장과 거리에서 한마음으로 응원하는 모습은 매우 인상적이었고, “붉은 물결”이라고 불릴 정도였습니다.
이 장면들은 방송을 통해 전 세계에 퍼지며 한국 사회의 응집력과 열정을 보여 주었습니다.

4. 히딩크 감독의 리더십
당시 거스 히딩크 감독은 한국 대표팀의 체력, 조직력, 전술을 크게 끌어올렸습니다.
이전의 한국 축구와는 다른, 강한 압박과 빠른 움직임을 보여 주면서 “한국 축구를 바꿨다”는 평가를 받았습니다.
히딩크라는 이름 자체가 하나의 사회적 신드롬이 되기도 했습니다.

5. 강팀들을 상대로 한 인상적인 경기
한국은 조별리그에서 포르투갈을 꺾었고, 16강에서는 이탈리아, 8강에서는 스페인을 상대로 승리했습니다.
특히 이탈리아전의 안정환 골든골, 스페인전의 승부차기 승리는 매우 극적이어서 오래 기억에 남았습니다.
이런 극적인 승부가 화제성을 더욱 키웠습니다.

6. 논란까지 포함한 엄청난 주목
한편으로는 일부 판정 논란도 있었습니다.
이탈리아전과 스페인전에서는 심판 판정이 국제적으로 큰 토론거리가 되었고, 이 때문에 한국의 경기들은 더 큰 관심을 받았습니다.
즉, 실력과 감동뿐 아니라 논쟁성까지 더해져서 훨씬 더 화제가 됐습니다.

7. 한국 사회 전체를 하나로 묶은 사건
2002년 월드컵은 단순한 스포츠 대회를 넘어, 한국 사회 전체가 함께 열광한 국가적 이벤트였습니다.
세대와 지역을 넘어 모두가 거리로 나와 응원했고, 이는 당시 한국의 집단적 자신감과 활력을 상징하는 장면이 되었습니다.

정리하면, 한국이 화제가 된 이유는
“공동 개최국이 예상 밖의 4강 신화를 쓰고, 강팀들을 꺾었으며, 거리응원 문화와 히딩크 리더십, 그리고 판정 논란까지 더해져 전 세계의 시선을 집중시켰기 때문”입니다.

원하시면 제가 이 내용을 더 짧게 요약하거나, 초등학생도 이해하기 쉽게 풀어서 다시 설명해 드릴게요.

프롬프트 엔지니어링 연습

In [44]:
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role": "system",
            "content": "<정해주고 싶은 역할>"
        },
        {
            "role": "user",
            "content": "<작성하고 싶은 Prompt>"
        }
    ]
)

뉴스요약 서비스 구현

In [49]:
# 시스템 프롬프트에 뉴스가 들어오면 주제, 요약, 가능 한 질문 세가지 출력 지정
def return_answer(input_text=''):
    system_prompt = """특정 문서가 입력되면 다음과 같은 형태로 문서를 분석하십시오.

1. 주어진 입력에 대해서 반드시 주제, 요약, 가능한 질문 이 세 가지를 순차적으로 작성해야 합니다.
2. 주제는 입력 문서의 주제를 한 줄로 요약합니다.
3. 요약은 입력 문서를 5줄로 요약합니다.
4. 가능한 질문은 입력 문서로부터 사람들이 할 수 있는 질문 세 가지를 파이썬 리스트 형태로 작성합니다.
5. 가능한 질문은 반드시 ["질문 1", "질문 2", "질문 3"]과 같이 파이썬 리스트 형태로 작성되어야 하는 점에 유의하십시오.

이제 시작합니다.
"""

    user_content = "입력: " + input_text + "\n주제:"

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content}
        ]
    )

    return response.choices[0].message.content

# 뉴스기사를 입력에 넣음
test = '''새처럼 움직이는 항공 로봇 '레이븐'.

스위스 로잔 연방 공대(EPFL) 신원동 박사 팀이 개발했는데요.

연구팀은 새의 엉덩이와 발목, 발을 참고해 뒷다리를 만들었습니다.

실제 새처럼 땅에서 걷고, 틈새를 건너뛰고, 위로 뛰어오릅니다.

껑충 뛰면서 날아오르는 이 기능이 핵심인데요.

기존 고정익 항공기처럼 지상을 달리지 않고 제자리에서 날아오릅니다.

연구팀은 레이븐의 점프 이륙이 점프하지 않고 날아오를 때보다 에너지 효율이 더 높다고 설명했는데요.

또 기존 고정익 항공기에 이 기능을 도입하면 복잡한 지형에서도 효율적으로 쓸 수 있을 거라고 덧붙였습니다.

#새 #로봇 #항공 #공대 #스위스 #신원동 #박사 #점프
'''

result = return_answer(input_text=test)
print(result)

주제: 새의 다리 구조를 모방해 점프 이륙이 가능한 항공 로봇 '레이븐' 개발

요약:
1. 스위스 로잔 연방 공대(EPFL) 신원동 박사 팀이 새처럼 움직이는 항공 로봇 '레이븐'을 개발했습니다.
2. 연구팀은 새의 엉덩이, 발목, 발 구조를 참고해 로봇의 뒷다리를 설계했습니다.
3. 레이븐은 실제 새처럼 땅에서 걷고, 틈새를 건너뛰며, 위로 뛰어오를 수 있습니다.
4. 특히 제자리에서 껑충 뛰어 날아오르는 점프 이륙 기능이 핵심입니다.
5. 연구팀은 이 방식이 기존 방식보다 에너지 효율이 높고, 복잡한 지형에서도 활용도가 높다고 설명했습니다.

가능한 질문:
["레이븐은 어떤 방식으로 이륙하나요?", "연구팀이 레이븐의 다리를 설계할 때 참고한 것은 무엇인가요?", "점프 이륙 기능이 기존 고정익 항공기보다 어떤 장점이 있나요?"]

키워드 추출 서비스

In [51]:
# 시스템 프롬프트 중간에 [Example] 이라는 내용과 함께 사용자의 입력과 답변을 예시로 기재
def return_answer(input_text):
    system_prompt = """You are an expert at extracting keywords from a given sentence. Extract keywords from a given sentence that are key to the context.

[Example]
input: '외신에 따르면 중국 이카이 글로벌 보도를 인용해 모더나가 중국 전용 mRNA 백신 개발을 위해 중국에 최대 10억 달러(약 1조 3017억 원)를 투자하기로 했다고 보도했다.'
keyword: ['모더나', 'mRNA', '1조 3017억 원']

Now the sentence you want to extract keywords from. The output format must be a list in Python.
"""

    user_content = "input: " + input_text + "\nkeyword: "

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content}
        ],
    )

    return response.choices[0].message.content

# 입력
text = '''3일 업계에 따르면 서울 신라호텔의 더 파크뷰는 12월 120일 저녁 가격을 19만 5000원으로, 2131일 저녁 가격을 21만 5000원으로 각각 인상한다. 평소 평일·주말 저녁 가격이 18만 5000원이던 것을 고려하면 각각 1만 원과 3만 원 올랐다. 가격 인상에도 불구하고 더 파크뷰의 12월 주말 예약은 대부분 찼고 12월 평일 예약 역시 빠르게 마감되고 있다고 신라호텔 측은 전했다.

롯데호텔 서울의 뷔페 라세느는 12월 평일·주말 저녁 가격을 19만 원으로 기존 대비 1만 원 올린다. 크리스마스 연휴 때인 2325일과 연말 3031일 저녁 가격은 20만 5000원이다. 롯데호텔 서울의 라세느도 현재 크리스마스 이브인 12월 24일과 크리스마스 당일인 12월 25일 예약은 대부분 마감됐다.

워커힐 호텔앤리조트는 그랜드 워커힐에서 운영하던 더뷔페를 비스타 워커힐로 확장 이전해 이날 가격을 올렸다. 평일·주말 저녁 가격은 15만 9000원에서 18만 9000원으로 3만 원 인상됐다. 다만 워커힐은 이번 가격 책정에 인플레이션(물가 상승)을 미리 반영한 만큼 연말을 앞두고 추가 인상을 단행하지 않을 계획이라고 밝혔다.

그랜드 인터컨티넨탈 서울 파르나스와 인터컨티넨탈 서울 코엑스도 다음주께 인상된 가격을 공지할 계획이다.
'''

result = return_answer(input_text=text)
print(result)

['서울 신라호텔', '더 파크뷰', '롯데호텔 서울', '라세느', '워커힐 호텔앤리조트', '더뷔페', '비스타 워커힐', '그랜드 인터컨티넨탈 서울 파르나스', '인터컨티넨탈 서울 코엑스', '가격 인상', '12월', '크리스마스', '연말', '인플레이션']

감성 분석 서비스


주어진 뉴스 기사가 긍정적인 뉴스인지 부정적인 뉴스인지

둘 다 아닌 중립에 해당하는 뉴스 기 사인지를 판단하는 감성 분석 서비스

In [53]:
# 가상의 회사 씨씨에스라는 회사가 주가가 상한가라는 텍스트를 함수의 입력으로 사용하여 답변
def return_label(text):
    prompt = '''주어진 텍스트가 긍정인지 중립인지 부정인지 예측하시오. 당신의 답변은 오로지 [positive, negative, neutral] 셋 중 하나여야만 합니다.

ex) 'SK하이닉스가 2분기 실적에서 역대 최고를 기록하였다' => "positive"
'''

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": text + " => "}
        ]
    )

    return response.choices[0].message.content


result = return_label(
    '씨씨에스로고 씨씨에스 주가가 상한가다. 3일 기준 씨씨에스는 29.84%(825원) 상승한 3590원에 거래를 마쳤다. 상온 초전도체 이슈가 부각되면서 주가가 연일 영향을 받는 모양새다.'
)

print(result)

positive

현업 엔지니어들의 사용방법

In [60]:
"""
[공장 고장 데이터 자동 분류 문제 정리]

■ 문제
- 공장에는 설비 기사들이 작성한 '고장내용' 데이터가 수만 건 존재하며 계속 증가함
- 사람마다 작성 방식이 달라 규칙 기반으로 '고장부품', '불량유형', '조치내용'을 추출하기 어려움
- 목표: 고장내용만 입력하면 나머지 3개 항목을 자동으로 분류하는 시스템 구축

■ 제약
- 공장 내부는 인터넷 사용 불가
- GPU 없음 → 딥러닝 모델 학습/서빙 어려움
- 라벨링된 데이터도 거의 없음

■ 해결 아이디어
1. 일부 데이터(약 4,000건)를 외부로 반출
2. 그 중 극소량(약 2건)만 사람이 직접 라벨링
3. GPT API를 활용하여 나머지 데이터의 라벨을 자동 생성 (합성 데이터 생성)
4. 생성된 데이터를 기반으로 가벼운 모델 학습
5. 학습된 모델을 공장 내부에 배포하여 실시간 자동 분류 수행

■ 핵심 포인트
- LLM(GPT)을 직접 서비스에 쓰는 것이 아니라 "데이터 생성 도구"로 활용
- 이후에는 로컬 환경에서도 동작 가능한 경량 모델로 운영 가능
"""



import pandas as pd
import ast

# 데이터를 리스트 형태로 정리
data = {
    "수리일자": [
        "2023-09-07", "2021-10-08", "2022-02-23", "2022-04-06",
        "2021-02-20", "2021-02-26", "2021-04-13", "2021-07-30",
        "2022-07-12", "2022-07-13", "2022-07-18", "2022-07-18",
        "2022-08-11", "2022-09-13", "2022-10-04", "2022-10-26",
        "2022-11-11", "2022-11-14"
    ],
    "고장내용": [
        "출하장 입구 에어 50A 유니온 에어리크 재조임",
        "SHIELD ROOM 화풍기 철거부위 마감, 판넬 벽체 문 타공",
        "F/P 기능상실 PLC 확인 및 클램프 감지센서 조정",
        "와이어 전진 동작 이상 점검 중 정상 작동됨",
        "클램프 기동 이상 오일보충 에어 제거",
        "피이더 조작판 매입 콘센트 고정",
        "QDC 파손 클램프 교체",
        "광센서 고정블록 볼트 마모 600ton 것으로 대체",
        "휠 회전 작동 불량 점검 세기정공 AS 요청",
        "클러치 ASS'Y 작동 이상 분해 출문 (세기정공)",
        "클러치 assy 불량으로 전자접촉기 교체",
        "클러치 밋션 기어오일 보출 ATF-3",
        "휨가지 센서 단선 교체",
        "안전 1행정 타발 정지 위치 이상 리미트 캠 스위치 교체 및 조정, 상사점 리미트 스위치 교체",
        "QDC 클램프 기동 이상 에어 빼기",
        "피이더 소재 진입 이상 캠 스위치 조정",
        "카운터 완료 시 정지 시점 불량 카운터 각도 조정",
        "NC FEEDER 코일 이송거리 이상 재세팅"
    ],
    "고장부품": [
        None if x in [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] else x
        for x in ["50A 유니온", "SHIELD ROOM 화풍기"] + [None] * 16
    ],
    "불량유형": [
        None if x in [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] else x
        for x in ["에어리크", "철거부위 마감"] + [None] * 16
    ],
    "조치내용": [
        None if x in [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17] else x
        for x in ["재조임", "판넬 벽체 문 타공"] + [None] * 16
    ]
}

# 데이터프레임 생성
df = pd.DataFrame(data)

# 유형, 조치 내용이 존재하지 않는 데이터에 대해서만 필터링하여 sub_df 에 저장
sub_df = df[df['고장부품'].isnull()]
sub_df.reset_index(drop=True, inplace=True)
sub_df

,수리일자,고장내용,고장부품,불량유형,조치내용
0,2022-02-23,F/P 기능상실 PLC 확인 및 클램프 감지센서 조정,NaN,NaN,NaN
1,2022-04-06,와이어 전진 동작 이상 점검 중 정상 작동됨,NaN,NaN,NaN
2,2021-02-20,클램프 기동 이상 오일보충 에어 제거,NaN,NaN,NaN
3,2021-02-26,피이더 조작판 매입 콘센트 고정,NaN,NaN,NaN
4,2021-04-13,QDC 파손 클램프 교체,NaN,NaN,NaN
5,2021-07-30,광센서 고정블록 볼트 마모 600ton 것으로 대체,NaN,NaN,NaN
6,2022-07-12,휠 회전 작동 불량 점검 세기정공 AS 요청,NaN,NaN,NaN
7,2022-07-13,클러치 ASS'Y 작동 이상 분해 출문 (세기정공),NaN,NaN,NaN
8,2022-07-18,클러치 assy 불량으로 전자접촉기 교체,NaN,NaN,NaN
9,2022-07-18,클러치 밋션 기어오일 보출 ATF-3,NaN,NaN,NaN
10,2022-08-11,휨가지 센서 단선 교체,NaN,NaN,NaN
11,2022-09-13,"안전 1행정 타발 정지 위치 이상 리미트 캠 스위치 교체 및 조정, 상사점 리미트 ...",NaN,NaN,NaN
12,2022-10-04,QDC 클램프 기동 이상 에어 빼기,NaN,NaN,NaN
13,2022-10-26,피이더 소재 진입 이상 캠 스위치 조정,NaN,NaN,NaN
14,2022-11-11,카운터 완료 시 정지 시점 불량 카운터 각도 조정,NaN,NaN,NaN
15,2022-11-14,NC FEEDER 코일 이송거리 이상 재세팅,NaN,NaN,NaN

In [62]:
# 고장내용 열 전체를 inputs 라는 파이썬 리스트에 저장
inputs= sub_df['고장내용'].to_list()
print(inputs)

['F/P 기능상실 PLC 확인 및 클램프 감지센서 조정', '와이어 전진 동작 이상 점검 중 정상 작동됨', '클램프 기동 이상 오일보충 에어 제거', '피이더 조작판 매입 콘센트 고정', 'QDC 파손 클램프 교체', '광센서 고정블록 볼트 마모 600ton 것으로 대체', '휠 회전 작동 불량 점검 세기정공 AS 요청', "클러치 ASS'Y 작동 이상 분해 출문 (세기정공)", '클러치 assy 불량으로 전자접촉기 교체', '클러치 밋션 기어오일 보출 ATF-3', '휨가지 센서 단선 교체', '안전 1행정 타발 정지 위치 이상 리미트 캠 스위치 교체 및 조정, 상사점 리미트 스위치 교체', 'QDC 클램프 기동 이상 에어 빼기', '피이더 소재 진입 이상 캠 스위치 조정', '카운터 완료 시 정지 시점 불량 카운터 각도 조정', 'NC FEEDER 코일 이송거리 이상 재세팅']

In [64]:
# 2건의 예시를 작성
def return_label(text):
    prompt = '''주어진 고장내용 텍스트로부터 고장부품, 불량유형, 조치내용을 추출하시오.
이때 파이썬의 Dictionary 형태로 반환하시오.

ex)
고장내용: '출하장 입구 에어 50A 유니온 에어리크 재조임'
출력: {"고장부품": "50A 유니온", "불량유형": "에어리크", "조치내용": "재조임"}

고장내용: 'SHIELD ROOM 화풍기 철거부위 마감, 판넬 벽체 문 타공'
출력: {"고장부품": "SHIELD ROOM 화풍기", "불량유형": "철거부위 마감", "조치내용": "판넬 벽체 문 타공"}
'''

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": "고장내용: " + text + "\n출력: "}
        ],
    )

    return response.choices[0].message.content

In [65]:
# 반복문을 활용하여 GPT 연속 호출
result = []
for input in inputs:
  result.append(return_label(input))

In [66]:
print(result)

['{"고장부품": "F/P", "불량유형": "기능상실", "조치내용": "PLC 확인 및 클램프 감지센서 조정"}', '{"고장부품": "와이어", "불량유형": "전진 동작 이상", "조치내용": "점검 중 정상 작동됨"}', '{"고장부품": "클램프", "불량유형": "기동 이상", "조치내용": "오일보충, 에어 제거"}', '{"고장부품": "피이더 조작판 매입 콘센트", "불량유형": "고정", "조치내용": ""}', '{"고장부품": "QDC", "불량유형": "파손", "조치내용": "클램프 교체"}', '{"고장부품": "광센서 고정블록 볼트", "불량유형": "마모", "조치내용": "600ton 것으로 대체"}', '{"고장부품": "휠", "불량유형": "회전 작동 불량", "조치내용": "점검 세기정공 AS 요청"}', '{"고장부품": "클러치 ASS\'Y", "불량유형": "작동 이상", "조치내용": "분해 출문"}', '{"고장부품": "클러치 assy", "불량유형": "불량", "조치내용": "전자접촉기 교체"}', '{"고장부품": "클러치 밋션", "불량유형": "기어오일 보출", "조치내용": "ATF-3"}', '{"고장부품": "휨가지 센서", "불량유형": "단선", "조치내용": "교체"}', '```python\n{\n    "고장부품": "리미트 캠 스위치, 상사점 리미트 스위치",\n    "불량유형": "타발 정지 위치 이상",\n    "조치내용": "교체 및 조정, 교체"\n}\n```', '{"고장부품": "QDC 클램프", "불량유형": "기동 이상", "조치내용": "에어 빼기"}', '{"고장부품": "피이더 소재", "불량유형": "진입 이상", "조치내용": "캠 스위치 조정"}', '{"고장부품": "카운터", "불량유형": "정지 시점 불량", "조치내용": "각도 조정"}', '{"고장부품": "NC FEEDER 코일", "불량유형": "이송거리 이상", "조치내용": "재세팅"}']

 이렇게 하면 고장부품, 불량 유형, 조치사항이 기재된

 4,000 건의 데이터를 얻을 수 있음.

# 랭체인 RAG 실습

In [16]:
pip install -U langchain-community

Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-core<2.0.0,>=1.0.1 (from langchain-community)
  Downloading langchain_core-1.2.21-py3-none-any.whl.metadata (4.4 kB)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.3-py3-none-any.whl.metadata (4.8 kB)
Collecting SQLAlchemy<3.0.0,>=1.4.0 (from langchain-community)
  Downloading sqlalchemy-2.0.48-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (6.0.3)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community)
  Downloading aiohttp-3.13.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-community)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.13.1-py3-none-any.whl.metadata (3.4 kB)
Collecting langsmith<1.0.0,>=0.1.125 (from langchain-community)
  Downloading langsmith-0.7.22-py3-none-any.whl.metadata (15 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=1.26.2 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (1.26.4)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading yarl-1.23.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 kB 9.9 MB/s eta 0:00:00
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.1 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./tf-env/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.12.5)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.0.1->langchain-community)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: packaging>=23.2.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (4.15.0)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.0.1->langchain-community)
  Downloading uuid_utils-0.14.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Collecting orjson>=3.9.14 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading orjson-3.11.7-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 6.8 MB/s eta 0:00:00
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting xxhash>=3.0.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain-community)
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: typing-inspection>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.2.25)
Collecting greenlet>=1 (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community)
  Downloading greenlet-3.3.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: anyio in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: httpcore==1.* in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./tf-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in ./tf-env/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain-community) (3.1.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.41.5)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 41.2 MB/s eta 0:00:00
Downloading aiohttp-3.13.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 43.8 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.3-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 44.4 MB/s eta 0:00:00
Downloading langchain_core-1.2.21-py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.8/505.8 kB 41.0 MB/s eta 0:00:00
Downloading langsmith-0.7.22-py3-none-any.whl (359 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 359.9/359.9 kB 35.8 MB/s eta 0:00:00
Downloading pydantic_settings-2.13.1-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.9/58.9 kB 4.8 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.48-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 44.5 MB/s eta 0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 kB 31.6 MB/s eta 0:00:00
Downloading greenlet-3.3.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (613 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.9/613.9 kB 28.6 MB/s eta 0:00:00
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langchain_text_splitters-1.1.1-py3-none-any.whl (35 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 4.4 MB/s eta 0:00:00
Downloading multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.3/256.3 kB 33.5 MB/s eta 0:00:00
Downloading orjson-3.11.7-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 21.6 MB/s eta 0:00:00
Downloading propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (221 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.6/221.6 kB 31.0 MB/s eta 0:00:00
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 9.8 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading uuid_utils-0.14.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.7/345.7 kB 37.4 MB/s eta 0:00:00
Downloading xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.9/193.9 kB 27.0 MB/s eta 0:00:00
Downloading yarl-1.23.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.1/100.1 kB 9.3 MB/s eta 0:00:00
Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 40.1 MB/s eta 0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: zstandard, xxhash, uuid-utils, tenacity, python-dotenv, propcache, orjson, mypy-extensions, multidict, marshmallow, jsonpatch, httpx-sse, greenlet, frozenlist, aiohappyeyeballs, yarl, typing-inspect, SQLAlchemy, requests-toolbelt, aiosignal, pydantic-settings, langsmith, dataclasses-json, aiohttp, langchain-core, langchain-text-splitters, langchain-classic, langchain-community
Successfully installed SQLAlchemy-2.0.48 aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 dataclasses-json-0.6.7 frozenlist-1.8.0 greenlet-3.3.2 httpx-sse-0.4.3 jsonpatch-1.33 langchain-classic-1.0.3 langchain-community-0.4.1 langchain-core-1.2.21 langchain-text-splitters-1.1.1 langsmith-0.7.22 marshmallow-3.26.2 multidict-6.7.1 mypy-extensions-1.1.0 orjson-3.11.7 propcache-0.4.1 pydantic-settings-2.13.1 python-dotenv-1.2.2 requests-toolbelt-1.0.0 tenacity-9.1.4 typing-inspect-0.9.0 uuid-utils-0.14.1 xxhash-3.6.0 yarl-1.23.0 zstandard-0.25.0
Note: you may need to restart the kernel to use updated packages.

In [67]:
# 코사인 유사도 구하기 -1~ 1
# 벡터 A, B 의 코사인
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))

vec1 = np.array([0, 1, 1, 1])
vec2 = np.array([1, 0, 1, 1])
vec3 = np.array([2, 0, 2, 2])

print('벡터 1과 벡터 2의 유사도:', cos_sim(vec1, vec2))
print('벡터 1과 벡터 3의 유사도:', cos_sim(vec1, vec3))
print('벡터 2와 벡터 3의 유사도:', cos_sim(vec2, vec3))

벡터 1과 벡터 2의 유사도: 0.6666666666666667
벡터 1과 벡터 3의 유사도: 0.6666666666666667
벡터 2와 벡터 3의 유사도: 1.0000000000000002

In [ ]:
# # https://developers.openai.com/api/docs/guides/embeddings?lang=python
# from openai import OpenAI
# client = OpenAI()

# response = client.embeddings.create(
#     input="Your text string goes here",
#     model="text-embedding-3-small"
# )

# print(response.data[0].embedding)

In [24]:
pip install langchain-openai

Collecting langchain-openai
  Downloading langchain_openai-1.1.12-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.21 in ./tf-env/lib/python3.12/site-packages (from langchain-openai) (1.2.21)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in ./tf-env/lib/python3.12/site-packages (from langchain-openai) (2.29.0)
Collecting tiktoken<1.0.0,>=0.7.0 (from langchain-openai)
  Downloading tiktoken-0.12.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.21->langchain-openai) (0.14.1)
Requirement already satisfied: anyio<5,>=3.5.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.13.0)
Requirement already satisfied: sniffio in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.67.3)
Requirement already satisfied: regex>=2022.1.18 in ./tf-env/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.2.28)
Requirement already satisfied: requests>=2.26.0 in ./tf-env/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.32.5)
Requirement already satisfied: idna>=2.8 in ./tf-env/lib/python3.12/site-packages (from anyio<5,>=3.5.0->openai<3.0.0,>=2.26.0->langchain-openai) (3.11)
Requirement already satisfied: certifi in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./tf-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in ./tf-env/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.21->langchain-openai) (3.1.0)
Requirement already satisfied: orjson>=3.9.14 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-openai) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-openai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-openai) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-openai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-openai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./tf-env/lib/python3.12/site-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain-openai) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./tf-env/lib/python3.12/site-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.6.3)
Downloading langchain_openai-1.1.12-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 5.6 MB/s eta 0:00:00
Downloading tiktoken-0.12.0-cp312-cp312-manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 32.1 MB/s eta 0:00:00
Installing collected packages: tiktoken, langchain-openai
Successfully installed langchain-openai-1.1.12 tiktoken-0.12.0
Note: you may need to restart the kernel to use updated packages.

In [25]:
import sys
print(sys.executable)

/home/junsu/tf-env/bin/python3.12

In [68]:
import os
import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd
from langchain_openai import OpenAIEmbeddings
# 키확인
os.environ['OPENAI_API_KEY'] = ""

In [69]:
# 임베딩 모델 설정 (최신 모델: text-embedding-3-small)
# 이후 유사도 계산을 위한 벡터 생성
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

query_result = embeddings.embed_query("저는 배가 고파요")

print(query_result)

[0.017364501953125, -0.0078582763671875, -0.0290985107421875, 0.0075531005859375, 0.00115203857421875, -0.058746337890625, -0.033721923828125, 0.033599853515625, -0.0467529296875, -0.01544189453125, -0.02069091796875, 0.051239013671875, -0.0013132095336914062, -0.0038471221923828125, -0.0169677734375, 0.002384185791015625, -0.05816650390625, 0.00034999847412109375, 0.004978179931640625, -0.03277587890625, -0.0245513916015625, -0.0157623291015625, -0.023284912109375, -0.006778717041015625, 0.0020580291748046875, -0.00034737586975097656, 0.039581298828125, -0.033721923828125, 0.0036334991455078125, -0.01157379150390625, 0.00989532470703125, -0.04766845703125, 0.0180511474609375, -0.0484619140625, -0.01898193359375, -0.0386962890625, 0.011688232421875, -0.037689208984375, -0.00418853759765625, 0.0011758804321289062, -0.029205322265625, 0.0015573501586914062, -0.0179901123046875, 0.008941650390625, 0.03289794921875, 0.036041259765625, -0.005748748779296875, 0.01514434814453125, 0.051727294921875, 0.00839996337890625, -0.014190673828125, 0.01036834716796875, 0.0093536376953125, 0.0609130859375, 0.031646728515625, 0.007701873779296875, -0.00168609619140625, 0.010894775390625, -0.016021728515625, -0.01219940185546875, -0.0163726806640625, 0.0074462890625, -0.0247039794921875, 0.02166748046875, -0.00396728515625, -0.019683837890625, 0.0302734375, -0.04364013671875, -0.013885498046875, 0.01183319091796875, 0.0066375732421875, -0.00687408447265625, -0.041900634765625, 0.0070953369140625, 0.0158233642578125, -0.00218963623046875, 0.0015592575073242188, -0.0268096923828125, 0.03887939453125, 0.0199432373046875, 0.020294189453125, 0.06829833984375, 0.0263519287109375, -0.05609130859375, -0.0209808349609375, -0.060791015625, -0.07110595703125, -0.000995635986328125, -0.01165771484375, 0.019866943359375, -0.01126861572265625, 0.0243682861328125, 0.0244140625, 0.019012451171875, -0.0268096923828125, -0.0009627342224121094, -0.002429962158203125, -0.0161285400390625, -0.004032135009765625, 0.01154327392578125, 0.03887939453125, 0.0277557373046875, 0.00897979736328125, 0.0052032470703125, 0.045745849609375, 0.004650115966796875, 0.01319122314453125, -0.0177001953125, -0.049652099609375, 0.010284423828125, -0.01812744140625, 0.034759521484375, 0.0206451416015625, -0.02349853515625, -0.02471923828125, 0.0309906005859375, 0.0084686279296875, 0.0006761550903320312, -0.0037517547607421875, -0.0537109375, 0.03765869140625, 0.042083740234375, 0.005649566650390625, -0.053985595703125, -0.0186004638671875, 0.007843017578125, -0.01837158203125, 0.00804901123046875, -0.03045654296875, 0.06439208984375, -0.00856781005859375, -0.0261383056640625, 0.03692626953125, -0.022796630859375, -0.0012845993041992188, 0.034149169921875, -0.03973388671875, -0.0187225341796875, -0.03228759765625, -0.0233154296875, 0.0243682861328125, 0.007633209228515625, 0.0207977294921875, -0.0012903213500976562, -0.0208587646484375, -0.025299072265625, 0.0285491943359375, 0.08685302734375, -0.01727294921875, 0.053955078125, 0.005756378173828125, 0.006961822509765625, -0.0256500244140625, -0.0287933349609375, -0.01294708251953125, -0.01343536376953125, -0.051239013671875, 0.061981201171875, -0.01029205322265625, 0.047821044921875, 0.01119232177734375, 0.00818634033203125, 0.0268707275390625, 0.019927978515625, -0.0008792877197265625, 0.0369873046875, -0.01165008544921875, 0.01541900634765625, -0.01200103759765625, -0.0330810546875, 0.0157470703125, 0.054718017578125, 0.010955810546875, -0.0300445556640625, -0.01468658447265625, -0.00624847412109375, 0.0007996559143066406, 0.039276123046875, -0.03851318359375, 0.021331787109375, -0.0007700920104980469, 0.0045013427734375, -0.007518768310546875, 0.0265960693359375, -0.035400390625, 0.006465911865234375, 0.071533203125, 0.041290283203125, -0.0022945404052734375, 0.00799560546875, 0.01209259033203125, 0.06195068359375, 0.0321044921875, -0.07232666015625, -0.03204345703125, -0.043365478515625, -0.01488494873046875, -0.050262451171875, -0.020721435546875, 0.02081298828125, 0.04742431640625, 0.01702880859375, 0.05401611328125, 0.0046844482421875, 0.0013418197631835938, 0.004589080810546875, -0.01520538330078125, -0.01629638671875, 0.0104217529296875, 0.007335662841796875, 0.0297088623046875, 0.0002758502960205078, -0.01503753662109375, 0.02252197265625, -0.0172882080078125, -0.0301971435546875, 0.083984375, 0.041473388671875, 0.033905029296875, 0.0290985107421875, 0.01861572265625, -0.0178375244140625, 0.0169677734375, -0.001079559326171875, 0.040771484375, 0.0506591796875, 0.06304931640625, -0.0164794921875, -0.00194549560546875, 0.0087890625, -0.01099395751953125, 0.041107177734375, -0.0099334716796875, -0.0452880859375, -0.0418701171875, 0.0299072265625, -0.0054168701171875, 0.00579071044921875, 0.0164794921875, -0.0286865234375, 0.00867462158203125, 0.046600341796875, 0.03887939453125, -0.00972747802734375, -0.010040283203125, 0.00817108154296875, 0.01263427734375, 0.0068511962890625, 0.018463134765625, 0.0548095703125, 0.02398681640625, 0.0296630859375, -0.0017843246459960938, -0.00615692138671875, -0.0259246826171875, 0.0086822509765625, -0.00811004638671875, 0.0044403076171875, -0.03631591796875, 0.004119873046875, 0.0439453125, -0.00652313232421875, -0.042816162109375, 0.011566162109375, -0.00183868408203125, 0.014312744140625, 0.057037353515625, -0.01398468017578125, 0.031494140625, 2.777576446533203e-05, -0.01081085205078125, -0.011505126953125, -0.0045928955078125, -0.0249176025390625, -0.04132080078125, 0.0085906982421875, -0.03173828125, 0.0031147003173828125, 0.01227569580078125, -0.05206298828125, -0.0009703636169433594, 0.0175323486328125, -0.01214599609375, -0.039031982421875, -0.010040283203125, 0.03643798828125, -0.02081298828125, 0.0096435546875, 0.0440673828125, -0.0267791748046875, 0.0218505859375, -0.0260162353515625, 0.004974365234375, 0.02197265625, 0.059417724609375, 0.01068115234375, 0.0088958740234375, 0.005077362060546875, 0.0306396484375, -0.0224456787109375, 0.038330078125, 0.0089263916015625, -0.00936126708984375, -0.006290435791015625, -0.02825927734375, -0.017913818359375, -0.0026187896728515625, -0.0035495758056640625, -0.0509033203125, 0.003009796142578125, -0.050689697265625, -0.01367950439453125, 0.041595458984375, -0.034637451171875, -0.002918243408203125, -0.00832366943359375, 0.01140594482421875, -0.014007568359375, 0.01479339599609375, -0.0171051025390625, 0.0584716796875, 0.0281982421875, -0.036346435546875, 0.062255859375, -0.005733489990234375, 0.0020084381103515625, 0.0238800048828125, -0.01418304443359375, 0.004772186279296875, -0.02545166015625, -0.034759521484375, 0.013336181640625, 0.0382080078125, -0.02587890625, 0.0259552001953125, -0.04473876953125, 0.017242431640625, -0.007389068603515625, -0.020599365234375, -0.0294342041015625, -0.0293731689453125, 0.005855560302734375, -0.01010894775390625, 0.0101776123046875, 0.002490997314453125, 0.03076171875, 0.063232421875, -0.0294952392578125, -0.035064697265625, -0.0328369140625, 0.06536865234375, 0.0022125244140625, 0.042266845703125, -0.01342010498046875, -0.005367279052734375, -0.0357666015625, 0.0150909423828125, 0.030487060546875, 0.00031638145446777344, 0.04632568359375, -0.061370849609375, 0.0089874267578125, -0.01444244384765625, -0.02197265625, 0.00365447998046875, -0.0161285400390625, -0.025970458984375, 0.01053619384765625, 0.0236968994140625, 0.042388916015625, -0.0289306640625, 0.0054931640625, -0.022369384765625, -0.001071929931640625, -0.0150909423828125, 0.00704193115234375, 0.0246734619140625, 0.0418701171875, -0.0246429443359375, 0.00875091552734375, -0.00960540771484375, 0.0169525146484375, -0.012939453125, 0.049774169921875, -0.00879669189453125, -0.035552978515625, -0.015472412109375, 0.0325927734375, 0.0278167724609375, 0.034576416015625, 0.0576171875, -0.004047393798828125, -0.005374908447265625, -0.0007562637329101562, -0.0352783203125, 0.0240478515625, -0.016571044921875, -0.0175628662109375, -0.059295654296875, -0.0268402099609375, -0.019866943359375, 0.0044097900390625, -0.06524658203125, -0.037109375, 0.0126953125, 0.00965118408203125, -0.039581298828125, 0.035003662109375, -0.007236480712890625, -0.03009033203125, 0.0167694091796875, 0.048675537109375, 0.04998779296875, 0.01235198974609375, 0.040496826171875, -0.0018405914306640625, -0.0127410888671875, 0.027252197265625, -0.00897216796875, 0.004642486572265625, 0.041534423828125, 0.06170654296875, -0.0543212890625, 0.00464630126953125, -0.057159423828125, 0.00254058837890625, 0.0011148452758789062, -0.005596160888671875, 0.06536865234375, -0.03271484375, 0.0249176025390625, 0.01324462890625, -0.03936767578125, -0.0103302001953125, -0.01092529296875, -0.07708740234375, -0.003910064697265625, 0.0166168212890625, 0.002826690673828125, -0.0241851806640625, 0.01305389404296875, -0.08489990234375, -0.01404571533203125, 0.0380859375, -0.021270751953125, 0.01446533203125, 0.0404052734375, -0.01200103759765625, -0.00940704345703125, -0.0229034423828125, 0.0496826171875, -0.0123138427734375, -0.005947113037109375, -0.0012826919555664062, -0.0207366943359375, 0.01149749755859375, 0.00030422210693359375, 0.01192474365234375, 0.018463134765625, -0.050048828125, -0.005123138427734375, 0.0438232421875, -0.0038967132568359375, 0.0199737548828125, 0.01468658447265625, -0.00984954833984375, 0.0173492431640625, 0.021759033203125, 0.00368499755859375, 0.004688262939453125, 0.00360107421875, 0.0156402587890625, -0.033355712890625, -0.044891357421875, 0.01108551025390625, 0.0299072265625, -0.070068359375, 0.004314422607421875, -0.0283660888671875, -0.0234375, 0.0062713623046875, 0.04547119140625, -0.0182647705078125, -0.02398681640625, 0.0031223297119140625, 0.108154296875, -0.007511138916015625, 0.02264404296875, -0.05206298828125, -0.031951904296875, 0.0214996337890625, 0.0013246536254882812, 0.068115234375, -0.0037078857421875, -0.010009765625, 0.006298065185546875, -0.074462890625, -0.013275146484375, -0.00930023193359375, 0.0026531219482421875, -0.0160675048828125, -0.01727294921875, 0.00231170654296875, -0.0175933837890625, 0.035369873046875, -0.005054473876953125, -0.00963592529296875, 0.01053619384765625, -0.00978851318359375, -0.00553131103515625, -0.01393890380859375, 0.0273284912109375, -0.01476287841796875, -0.00041961669921875, 0.01898193359375, -0.00269317626953125, -0.0015344619750976562, -0.016265869140625, 0.0175933837890625, 0.059326171875, -0.0299835205078125, -0.0046234130859375, 0.01525115966796875, -0.036895751953125, -0.004695892333984375, -0.0258636474609375, -0.002178192138671875, 0.0006208419799804688, 0.01012420654296875, 0.009185791015625, 0.004940032958984375, 0.0111541748046875, -0.01788330078125, -0.0302886962890625, -0.0082550048828125, -0.03314208984375, 0.00467681884765625, 0.0028095245361328125, 0.0107879638671875, 0.0206451416015625, -0.01558685302734375, -0.0011339187622070312, -0.038665771484375, 0.007442474365234375, 0.00324249267578125, -0.01023101806640625, 0.00848388671875, -0.02801513671875, 0.049896240234375, 0.047119140625, 0.00811767578125, -0.0012598037719726562, -0.0115509033203125, 0.0271148681640625, -0.02667236328125, -0.0261077880859375, -0.0145721435546875, 0.01324462890625, 0.0192718505859375, 0.034271240234375, -0.011138916015625, 0.010040283203125, 0.0281829833984375, 0.005748748779296875, -0.002536773681640625, -0.0307769775390625, 5.251169204711914e-05, -0.038482666015625, -0.01898193359375, 0.004817962646484375, -0.016937255859375, 0.037506103515625, -0.025238037109375, 0.0196685791015625, 0.007236480712890625, -0.01812744140625, 0.05694580078125, -0.0011234283447265625, -0.06085205078125, 0.0419921875, -0.033233642578125, -0.038909912109375, -0.0263519287109375, -0.0212860107421875, -0.025115966796875, 0.0069580078125, -0.038665771484375, -0.00864410400390625, 0.018798828125, -0.0070953369140625, 0.023284912109375, -0.007793426513671875, -0.006961822509765625, 0.00179290771484375, 0.01140594482421875, -0.0447998046875, -0.0357666015625, -0.00848388671875, 0.0229339599609375, -0.0174560546875, -0.0072021484375, -0.041839599609375, 0.020416259765625, 0.0210723876953125, 0.0140228271484375, -0.026275634765625, -0.0176849365234375, 0.00809478759765625, 0.0172576904296875, 0.01332855224609375, 0.003818511962890625, -0.01406097412109375, -0.0214385986328125, -0.0254669189453125, 0.00606536865234375, 0.0162811279296875, -0.03643798828125, -0.01027679443359375, -0.0007615089416503906, 0.0258026123046875, -0.00667572021484375, 0.02838134765625, 0.022674560546875, 0.0041656494140625, -0.020721435546875, 0.01259613037109375, 0.011505126953125, 0.022552490234375, -0.01300048828125, -0.003635406494140625, 0.005725860595703125, -0.058197021484375, -0.00830841064453125, 0.0225372314453125, 0.0019521713256835938, 0.0069732666015625, -0.004364013671875, -0.00945281982421875, -0.00775909423828125, 0.03167724609375, 0.0143280029296875, -0.0218353271484375, 0.01203155517578125, -0.0233612060546875, -0.01273345947265625, 0.03521728515625, -0.011749267578125, 0.01049041748046875, -0.005611419677734375, -0.0173797607421875, 0.049224853515625, 0.0167694091796875, -0.0025081634521484375, -0.0167236328125, -0.0217742919921875, 0.01922607421875, -0.019683837890625, -0.01385498046875, -0.003498077392578125, -0.00383758544921875, -0.0029354095458984375, 0.002483367919921875, -0.0108795166015625, -0.00655364990234375, 0.01467132568359375, 0.0251007080078125, -0.0186614990234375, 0.050323486328125, 0.006816864013671875, 0.008453369140625, 0.043792724609375, -0.0059661865234375, -0.00445556640625, -0.0017490386962890625, 0.052154541015625, 0.031829833984375, -0.0267181396484375, -0.01049041748046875, -0.0205230712890625, 0.024749755859375, -0.002231597900390625, 0.02606201171875, 0.0069122314453125, -0.0264892578125, 0.052886962890625, -0.0065155029296875, -0.01104736328125, -0.0115203857421875, 0.049285888671875, 0.004730224609375, -0.02117919921875, 0.0283355712890625, -0.004093170166015625, -0.0198974609375, 0.0040740966796875, 0.0230865478515625, 0.02099609375, -0.048095703125, -0.00438690185546875, 0.031707763671875, -0.01346588134765625, 0.00988006591796875, -0.01210784912109375, -0.0014524459838867188, -0.0099945068359375, 0.0077056884765625, 0.035614013671875, 0.012481689453125, 0.0011758804321289062, -0.03985595703125, -0.00452423095703125, -0.007144927978515625, -0.042694091796875, 0.0230255126953125, 0.0097198486328125, 0.020355224609375, -0.020599365234375, -0.019622802734375, -0.0241851806640625, -0.035552978515625, -0.0079193115234375, 0.053558349609375, -0.01438140869140625, -0.01110076904296875, 0.0095672607421875, -0.0364990234375, -0.021484375, -0.0025653839111328125, -0.013427734375, 0.01099395751953125, -0.00481414794921875, 0.012451171875, -0.0278167724609375, 0.0231475830078125, 0.0003476142883300781, 0.0247650146484375, -0.0355224609375, -0.012664794921875, 0.0244140625, -0.007686614990234375, -0.04315185546875, -0.03143310546875, 0.0123138427734375, -0.0158843994140625, 0.00197601318359375, 0.0186767578125, 0.001781463623046875, -9.709596633911133e-05, -0.01195526123046875, -0.031097412109375, -0.021392822265625, 0.0014219284057617188, 0.0202178955078125, -0.00786590576171875, 0.0262908935546875, 0.006259918212890625, 0.02734375, -0.06695556640625, 0.02899169921875, 0.00806427001953125, 0.04742431640625, -0.02081298828125, -0.025543212890625, 0.031494140625, 0.02862548828125, -0.0274200439453125, -0.00977325439453125, -0.0228118896484375, 0.000492095947265625, 0.01837158203125, 0.013153076171875, -0.0091094970703125, 0.037200927734375, 0.0053253173828125, 0.0251007080078125, -0.02532958984375, -0.0142059326171875, -0.006134033203125, 0.034698486328125, -0.01422119140625, 0.005664825439453125, -0.00441741943359375, -0.0214385986328125, 0.019989013671875, -0.02642822265625, -0.009918212890625, -0.01702880859375, -0.000865936279296875, -0.030853271484375, 0.018157958984375, -0.0217742919921875, -0.0236663818359375, -0.029937744140625, -0.007091522216796875, 0.0038623809814453125, 0.052001953125, 0.0037403106689453125, 0.0032978057861328125, -0.0177001953125, -0.019989013671875, 0.0167388916015625, -0.0294189453125, 0.043426513671875, -0.01052093505859375, 0.0061798095703125, -0.00262451171875, 0.0352783203125, 0.054168701171875, 0.0148468017578125, -0.037384033203125, 0.0010433197021484375, 0.0084991455078125, 0.01129150390625, 0.04071044921875, 0.001384735107421875, -0.00417327880859375, 0.005828857421875, -0.010772705078125, -0.006298065185546875, -0.0255279541015625, -0.00859832763671875, -0.01161956787109375, 0.0221710205078125, -0.0158843994140625, -0.01444244384765625, -0.0212860107421875, -0.0159149169921875, 0.005840301513671875, 0.026580810546875, 0.0684814453125, 0.01654052734375, -0.016357421875, -0.0268707275390625, -0.00508880615234375, -0.028900146484375, 0.0295867919921875, 0.051727294921875, -0.0103607177734375, -0.0012388229370117188, -0.0008068084716796875, -0.01349639892578125, 0.0156402587890625, 0.0313720703125, -0.019500732421875, -0.05120849609375, -0.0163726806640625, -0.0626220703125, 0.0004775524139404297, 0.0187225341796875, -0.0250396728515625, -0.0077362060546875, 0.00345611572265625, -0.002414703369140625, 0.005619049072265625, 0.03912353515625, 0.0008721351623535156, 0.037109375, 0.038238525390625, 0.0196380615234375, -0.0579833984375, -0.050933837890625, 0.02520751953125, -0.010772705078125, 0.022613525390625, 0.0007715225219726562, -0.0098419189453125, 0.00514984130859375, 0.0004096031188964844, -0.02423095703125, 0.0185394287109375, -0.029632568359375, -0.00269317626953125, -0.0226593017578125, -0.044525146484375, -0.002277374267578125, -0.004119873046875, -0.0031986236572265625, -0.0184173583984375, 0.004726409912109375, 0.0002371072769165039, 0.000762939453125, -0.035125732421875, 0.0173492431640625, 0.0269775390625, 0.0164642333984375, 0.019683837890625, 0.026519775390625, 0.0286712646484375, -0.01558685302734375, 0.03118896484375, -0.00860595703125, -0.0108489990234375, 0.00203704833984375, -0.0308990478515625, -0.0106658935546875, 0.00199127197265625, -0.0149383544921875, 0.03497314453125, 0.01273345947265625, -0.0419921875, 0.0190582275390625, 0.013427734375, 0.004535675048828125, -0.0014553070068359375, 0.0239105224609375, 0.00791168212890625, -0.031158447265625, 0.0151824951171875, 0.01100921630859375, -0.0306243896484375, 0.0110931396484375, 0.0034961700439453125, -0.0096435546875, 0.0014657974243164062, -0.0060272216796875, 0.00494384765625, -0.025543212890625, 0.03558349609375, -0.006290435791015625, -0.007099151611328125, -0.0364990234375, -0.01296234130859375, 0.005542755126953125, -0.00400543212890625, -0.004241943359375, -0.0187835693359375, -0.0011396408081054688, 0.01105499267578125, -0.0657958984375, 0.011077880859375, -0.006870269775390625, -0.0132598876953125, -0.001377105712890625, 0.010986328125, 0.033538818359375, -0.017425537109375, -0.0021381378173828125, -0.0165863037109375, -0.0244293212890625, -0.00888824462890625, -0.0205535888671875, 0.035247802734375, 0.0241851806640625, -0.02447509765625, 0.0242156982421875, -0.020233154296875, 0.0479736328125, -0.0032062530517578125, -0.0237274169921875, 0.0210113525390625, 0.0283660888671875, -0.034393310546875, -0.02191162109375, -0.029998779296875, 0.0311737060546875, 0.018157958984375, 0.037689208984375, -0.0079345703125, 0.00711822509765625, 0.01374053955078125, -0.0235748291015625, -0.03778076171875, -0.007205963134765625, -0.0633544921875, -0.026763916015625, -0.05401611328125, -0.014312744140625, -0.0213623046875, 0.035888671875, 0.02740478515625, -0.045745849609375, -0.01898193359375, 0.0269317626953125, 0.0260162353515625, 0.0283660888671875, -0.01031494140625, 0.004367828369140625, -0.015289306640625, -0.00905609130859375, 0.0171356201171875, 0.00457763671875, 0.021636962890625, 0.033355712890625, -0.007411956787109375, -0.0201568603515625, 0.0167694091796875, 0.062042236328125, -0.041717529296875, -0.0166168212890625, -0.027008056640625, 0.0207366943359375, 0.0268402099609375, 0.0247802734375, 0.019134521484375, 0.

In [72]:
# 임베딩 유사도 테스트를 위한 예제 문장 데이터 생성
# 다양한 의미(배: 음식 / 배: 선박 / 스팀: 게임 / 스팀: 요리)를 포함하도록 구성

data = [
    "저는 배가 고파요",
    "저기 배가 지나가네요",
    "굶어서 허기가 지네요",
    "허기워기라는 게임이 있는데 즐거워",
    "스팀에서 재밌는 거 해야지",
    "스팀 에어프라이어로 연어구이 해 먹을 거야"
]

# 데이터프레임 생성 (text 컬럼에 문장 저장)
df = pd.DataFrame(data, columns=["text"])

df

                      text
0                저는 배가 고파요
1              저기 배가 지나가네요
2              굶어서 허기가 지네요
3       허기워기라는 게임이 있는데 즐거워
4           스팀에서 재밌는 거 해야지
5  스팀 에어프라이어로 연어구이 해 먹을 거야

In [73]:
# 각 문장을 임베딩 모델을 통해 벡터로 변환하는 함수 정의
def get_embedding(text):
    return embeddings.embed_query(text)

# DataFrame의 text 컬럼에 대해 임베딩 수행
# 각 문장을 벡터로 변환하여 새로운 'embedding' 컬럼에 저장
df["embedding"] = df.apply(
    lambda row: get_embedding(row.text),
    axis=1
)

df

                      text                                          embedding
0                저는 배가 고파요  [0.0174102783203125, -0.0078125, -0.0290679931...
1              저기 배가 지나가네요  [0.03948974609375, 8.654594421386719e-05, -0.0...
2              굶어서 허기가 지네요  [0.041717529296875, 0.02508544921875, -0.01293...
3       허기워기라는 게임이 있는데 즐거워  [-0.0010433197021484375, 0.0008606910705566406...
4           스팀에서 재밌는 거 해야지  [0.01320648193359375, 0.0543212890625, -0.0402...
5  스팀 에어프라이어로 연어구이 해 먹을 거야  [0.0433349609375, 0.02398681640625, -0.0059967...

In [74]:
# 코사인 유사도 계산 함수
# 두 벡터(A, B) 간의 유사도를 계산 (값이 1에 가까울수록 유사)
def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))


# 질의(query)와 가장 유사한 문서를 찾는 함수
def return_answer_candidate(df, query):

    # 입력된 query를 임베딩 벡터로 변환
    query_embedding = get_embedding(query)

    # 각 문서의 임베딩과 query 임베딩 간의 유사도 계산
    # 계산된 유사도를 'similarity' 컬럼에 저장
    df["similarity"] = df["embedding"].apply(
        lambda x: cos_sim(np.array(x), np.array(query_embedding))
    )

    # 유사도가 높은 순으로 정렬 후 상위 3개 문서 선택
    top_three_doc = df.sort_values("similarity", ascending=False).head(3)

    return top_three_doc

In [75]:
# 질의 문장을 입력하여 유사한 문장 검색
sim_result = return_answer_candidate(
    df,
    "아무것도 안 먹었더니 꼬르륵 소리가 나네"
)

sim_result

,text,embedding,similarity
5,스팀 에어프라이어로 연어구이 해 먹을 거야,"[0.0433349609375, 0.02398681640625, -0.0059967...",0.322690
0,저는 배가 고파요,"[0.0174102783203125, -0.0078125, -0.0290679931...",0.248668
4,스팀에서 재밌는 거 해야지,"[0.01320648193359375, 0.0543212890625, -0.0402...",0.226086

임베딩 = 단어가 아니라 “의미”로 비교한다

# 청킹

Chunking = 긴 문서를 잘라서 나누는 것

■ 왜 자르냐?
- 너무 길면 AI가 이해 못하거나 성능 떨어짐

■ 문제
- 아무렇게나 자르면 의미가 깨짐

■ LangChain 방식
- 길이 기준 자르기 → 쉽지만 의미 깨짐
- 의미 기준 자르기 → 아직 성능 부족

■ 결론
- 기본 도구는 참고용
- 직접 잘 자르는 게 중요 (문단, 기준 등)

핵심: "어떻게 자르느냐가 성능을 결정한다"

In [77]:
# pip install langchain langchain-community

Collecting langchain
  Downloading langchain-1.2.13-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: langchain-community in ./tf-env/lib/python3.12/site-packages (0.4.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in ./tf-env/lib/python3.12/site-packages (from langchain) (1.2.21)
Collecting langgraph<1.2.0,>=1.1.1 (from langchain)
  Downloading langgraph-1.1.3-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./tf-env/lib/python3.12/site-packages (from langchain) (2.12.5)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (2.0.48)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (0.7.22)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in ./tf-env/lib/python3.12/site-packages (from langchain-community) (1.26.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in ./tf-env/lib/python3.12/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in ./tf-env/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: packaging>=23.2.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.2.0,>=1.1.1->langchain)
  Downloading langgraph_checkpoint-4.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.8 (from langgraph<1.2.0,>=1.1.1->langchain)
  Downloading langgraph_prebuilt-1.0.8-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.2.0,>=1.1.1->langchain)
  Downloading langgraph_sdk-0.3.12-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: xxhash>=3.5.0 in ./tf-env/lib/python3.12/site-packages (from langgraph<1.2.0,>=1.1.1->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in ./tf-env/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.2.25)
Requirement already satisfied: greenlet>=1 in ./tf-env/lib/python3.12/site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: anyio in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: httpcore==1.* in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./tf-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in ./tf-env/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.0)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.1->langchain)
  Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./tf-env/lib/python3.12/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Downloading langchain-1.2.13-py3-none-any.whl (112 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.5/112.5 kB 8.1 MB/s eta 0:00:00
Downloading langgraph-1.1.3-py3-none-any.whl (168 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.1/168.1 kB 19.2 MB/s eta 0:00:00
Downloading langgraph_checkpoint-4.0.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 7.1 MB/s eta 0:00:00
Downloading langgraph_prebuilt-1.0.8-py3-none-any.whl (35 kB)
Downloading langgraph_sdk-0.3.12-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 kB 12.5 MB/s eta 0:00:00
Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.6/212.6 kB 32.9 MB/s eta 0:00:00
Installing collected packages: ormsgpack, langgraph-sdk, langgraph-checkpoint, langgraph-prebuilt, langgraph, langchain
Successfully installed langchain-1.2.13 langgraph-1.1.3 langgraph-checkpoint-4.0.1 langgraph-prebuilt-1.0.8 langgraph-sdk-0.3.12 ormsgpack-1.12.2
Note: you may need to restart the kernel to use updated packages.

In [80]:
# 긴 길이를 가진 텍스트 데이터 다운로드
import urllib.request
# 구버전
# from langchain.text_splitter import RecursiveCharacterTextSplitter
# 최신
from langchain_text_splitters import RecursiveCharacterTextSplitter

# 텍스트 파일 다운로드
urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/lovit/soynlp/master/tutorials/2016-10-20.txt",
    filename="2016-10-20.txt"
)

# 파일 읽기
with open("2016-10-20.txt", encoding="utf-8") as f:
    file = f.read()

# 텍스트 길이 출력
print("텍스트의 길이:", len(file))

텍스트의 길이: 18085369

In [30]:
# lang chain text spliters
pip install -U langchain-text-splitters

Requirement already satisfied: langchain-text-splitters in ./tf-env/lib/python3.12/site-packages (1.1.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.13 in ./tf-env/lib/python3.12/site-packages (from langchain-text-splitters) (1.2.21)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in ./tf-env/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.1.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.4.2)
Requirement already satisfied: anyio in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (4.12.1)
Requirement already satisfied: certifi in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2026.2.25)
Requirement already satisfied: httpcore==1.* in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (1.0.9)
Requirement already satisfied: idna in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.11)
Requirement already satisfied: h11>=0.16 in ./tf-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./tf-env/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./tf-env/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-text-splitters) (2.6.3)
Note: you may need to restart the kernel to use updated packages.

# 길이 단위 청킹

In [82]:
# 텍스트를 일정 길이로 잘라주는 도구 생성
# chunk_size=500 → 한 덩어리를 최대 500자까지 자름
# chunk_overlap=0 → 덩어리끼리 겹치는 부분 없이 딱 끊어서 자름

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=0
)

In [83]:
# 텍스트를 여러 개의 작은 덩어리(청크)로 나눔
texts = text_splitter.create_documents([file])

# 나눠진 청크 개수 출력
print("분할된 청크의 수:", len(texts))

분할된 청크의 수: 47068

In [87]:
print(texts[1].page_content) #.page_content 원문 접근 # 1번 청크

오패산터널 총격전 용의자 검거 서울 연합뉴스 경찰 관계자들이 19일 오후 서울 강북구 오패산 터널 인근에서 사제 총기를 발사해 경찰을 살해한 용의자 성모씨를 검거하고 있다 성씨는 검거 당시 서바이벌 게임에서 쓰는 방탄조끼에 헬멧까지 착용한 상태였다 독자제공 영상 캡처 연합뉴스  서울 연합뉴스 김은경 기자 사제 총기로 경찰을 살해한 범인 성모 46 씨는 주도면밀했다  경찰에 따르면 성씨는 19일 오후 강북경찰서 인근 부동산 업소 밖에서 부동산업자 이모 67 씨가 나오기를 기다렸다 이씨와는 평소에도 말다툼을 자주 한 것으로 알려졌다  이씨가 나와 걷기 시작하자 성씨는 따라가면서 미리 준비해온 사제 총기를 이씨에게 발사했다 총알이 빗나가면서 이씨는 도망갔다 그 빗나간 총알은 지나가던 행인 71 씨의 배를 스쳤다  성씨는 강북서 인근 치킨집까지 이씨 뒤를 쫓으며 실랑이하다 쓰러뜨린 후 총기와 함께 가져온 망치로 이씨 머리를 때렸다  이 과정에서 오후 6시 20분께 강북구 번동 길 위에서

In [88]:
print(texts[2].page_content) # 2번 청크

사람들이 싸우고 있다 총소리가 났다 는 등의 신고가 여러건 들어왔다  5분 후에 성씨의 전자발찌가 훼손됐다는 신고가 보호관찰소 시스템을 통해 들어왔다 성범죄자로 전자발찌를 차고 있던 성씨는 부엌칼로 직접 자신의 발찌를 끊었다  용의자 소지 사제총기 2정 서울 연합뉴스 임헌정 기자 서울 시내에서 폭행 용의자가 현장 조사를 벌이던 경찰관에게 사제총기를 발사해 경찰관이 숨졌다 19일 오후 6시28분 강북구 번동에서 둔기로 맞았다 는 폭행 피해 신고가 접수돼 현장에서 조사하던 강북경찰서 번동파출소 소속 김모 54 경위가 폭행 용의자 성모 45 씨가 쏜 사제총기에 맞고 쓰러진 뒤 병원에 옮겨졌으나 숨졌다 사진은 용의자가 소지한 사제총기  신고를 받고 번동파출소에서 김창호 54 경위 등 경찰들이 오후 6시 29분께 현장으로 출동했다 성씨는 그사이 부동산 앞에 놓아뒀던 가방을 챙겨 오패산 쪽으로 도망간 후였다  김 경위는 오패산 터널 입구 오른쪽의 급경사에서 성씨에게 접근하다가 오후 6시

In [89]:
# 잘린 텍스트(청크)가 몇 글자인지 확인
print("1번 청크의 길이:", len(texts[1].page_content))
print("2번 청크의 길이:", len(texts[2].page_content))

1번 청크의 길이: 498
2번 청크의 길이: 496

#chunk_overlap

문장 안 끊기게 이어주는 옵션

In [94]:
pip install langchain langchain-openai langchain-text-splitters langchain-experimental

Requirement already satisfied: langchain in ./tf-env/lib/python3.12/site-packages (1.2.13)
Requirement already satisfied: langchain-openai in ./tf-env/lib/python3.12/site-packages (1.1.12)
Requirement already satisfied: langchain-text-splitters in ./tf-env/lib/python3.12/site-packages (1.1.1)
Collecting langchain-experimental
  Downloading langchain_experimental-0.4.1-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in ./tf-env/lib/python3.12/site-packages (from langchain) (1.2.21)
Requirement already satisfied: langgraph<1.2.0,>=1.1.1 in ./tf-env/lib/python3.12/site-packages (from langchain) (1.1.3)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./tf-env/lib/python3.12/site-packages (from langchain) (2.12.5)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in ./tf-env/lib/python3.12/site-packages (from langchain-openai) (2.29.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: langchain-community<1.0.0,>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from langchain-experimental) (0.4.1)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.0.48)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.7.22)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in ./tf-env/lib/python3.12/site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.26.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: packaging>=23.2.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in ./tf-env/lib/python3.12/site-packages (from langgraph<1.2.0,>=1.1.1->langchain) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in ./tf-env/lib/python3.12/site-packages (from langgraph<1.2.0,>=1.1.1->langchain) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in ./tf-env/lib/python3.12/site-packages (from langgraph<1.2.0,>=1.1.1->langchain) (0.3.12)
Requirement already satisfied: xxhash>=3.5.0 in ./tf-env/lib/python3.12/site-packages (from langgraph<1.2.0,>=1.1.1->langchain) (3.6.0)
Requirement already satisfied: anyio<5,>=3.5.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.13.0)
Requirement already satisfied: sniffio in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: regex>=2022.1.18 in ./tf-env/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.2.28)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.23.0)
Requirement already satisfied: idna>=2.8 in ./tf-env/lib/python3.12/site-packages (from anyio<5,>=3.5.0->openai<3.0.0,>=2.26.0->langchain-openai) (3.11)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in ./tf-env/lib/python3.12/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.9.0)
Requirement already satisfied: certifi in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./tf-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in ./tf-env/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.0)
Requirement already satisfied: ormsgpack>=1.12.0 in ./tf-env/lib/python3.12/site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.1->langchain) (1.12.2)
Requirement already satisfied: orjson>=3.11.5 in ./tf-env/lib/python3.12/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.1->langchain) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in ./tf-env/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.6.3)
Requirement already satisfied: greenlet>=1 in ./tf-env/lib/python3.12/site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.3.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./tf-env/lib/python3.12/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.1.0)
Downloading langchain_experimental-0.4.1-py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.1/210.1 kB 9.4 MB/s eta 0:00:00
Installing collected packages: langchain-experimental
Successfully installed langchain-experimental-0.4.1
Note: you may need to restart the kernel to use updated packages.

In [95]:
import os
import urllib.request

from langchain_openai.embeddings import OpenAIEmbeddings
from langchain_experimental.text_splitter import SemanticChunker

# # API 키 설정
# os.environ["OPENAI_API_KEY"] = "sk-"

# 텍스트 파일 다운로드
urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/chatgpt-kr/openai-api-tutorial/main/ch06/test.txt",
    filename="test.txt"
)

# 파일 읽기
with open("test.txt", encoding="utf-8") as f:
    file = f.read()

# 텍스트 길이 출력
print("텍스트의 길이:", len(file))

텍스트의 길이: 7460

#Semantic Chunker

의미 단위

In [96]:
# 의미 기준으로 텍스트를 나누는 청커 생성
text_splitter = SemanticChunker(OpenAIEmbeddings())

# 텍스트를 의미 단위로 분할
texts = text_splitter.create_documents([file])

# 나눠진 청크 개수 출력
print("분할된 청크의 수:", len(texts))

분할된 청크의 수: 10

In [105]:
# from langchain.schema import Document
from langchain_core.documents import Document

doc = Document(page_content="""그의 끈기와 열정은 주위 사람들에게 큰 귀감이 되었다. 교수들은 그를 "우리 학과의 보물"이라고 불렀고, 후배들은 그에게 조언을 구하기 위해 줄을 섰다. 졸업할 때 그는 학과 수석의 영예를 안았다.

직업과 해외 진출 시도

서울대를 졸업한 박민호는 큰 꿈을 안고 여러 IT 기업에 지원했다. 그는 자신의 능력을 인정받아 대기업에 입사할 수 있을 거라 믿었다.""")

doc

Document(metadata={}, page_content='그의 끈기와 열정은 주위 사람들에게 큰 귀감이 되었다. 교수들은 그를 "우리 학과의 보물"이라고 불렀고, 후배들은 그에게 조언을 구하기 위해 줄을 섰다. 졸업할 때 그는 학과 수석의 영예를 안았다.\n\n직업과 해외 진출 시도\n\n서울대를 졸업한 박민호는 큰 꿈을 안고 여러 IT 기업에 지원했다. 그는 자신의 능력을 인정받아 대기업에 입사할 수 있을 거라 믿었다.')

문서를 검색하기 좋게 잘라놓은 문서.

가장 비슷한 문서를 찾는다.

In [106]:
texts[4]

Document(metadata={}, page_content='그러나 현실은 냉혹했다. 연이은 탈락 통지에 그는 좌절감을 느꼈다. "내가 부족한 걸까?" 자신을 의심하기 시작했다. 결국 그는 작은 스타트업에서 일하기 시작했다. 급여는 많지 않았지만, 다양한 경험을 쌓을 수 있었다. 그는 이 시기를 자신의 실력을 갈고닦는 기회로 삼았다. 밤을 새워가며 새로운 기술을 익혔고, 회사 프로젝트에 혁신적인 아이디어를 제안했다. 2년이 지나자 그의 노력이 빛을 발하기 시작했다. 그가 개발한 알고리즘이 업계의 주목을 받게 된 것이다. 여러 기업에서 그에게 이직 제안을 해왔고, 그는 더 큰 회사로 옮길 수 있었다. 그러나 여전히 그의 꿈은 더 컸다. 그는 세계적인 IT 기업들이 모여 있는 미국 실리콘밸리로의 진출을 꿈꿨다. 수많은 지원서를 보냈지만, 대부분 거절당했다.')

In [107]:
texts[5]

Document(metadata={}, page_content='언어 장벽과 경력 부족이 주된 이유였다. 그러나 박민호는 포기하지 않았다. 퇴근 후에는 영어 학원에 다녔고, 주말에는 국제 컨퍼런스에 참가해 네트워크를 넓혔다. 이러한 노력 끝에 2010년, 그는 마침내 미국 실리콘밸리의 한 중소 IT 기업에 취직하게 되었다. 실리콘밸리에서의 첫 직장은 그에게 새로운 도전과 기회를 제공했다. 그는 자신의 꿈을 이루기 위한 첫 발걸음을 내딛었다는 생각에 가슴이 뛰었다. 해외에서의 도전과 성공\n미국에서의 생활은 결코 쉬운 일이 아니었다. 문화적 차이와 언어 장벽, 그리고 새로운 환경에 적응해야 했다. 처음 몇 달 동안 박민호는 매일 밤 한국으로 돌아가고 싶다는 생각을 했다. 회의 중 동료들의 농담을 이해하지 못해 웃지 못할 때도 많았고, 업무 지시를 제대로 이해하지 못해 실수를 저지르기도 했다. 그러나 박민호는 포기하지 않았다. 그는 퇴근 후에도 영어 공부를 계속했고, 주말에는 현지 문화를 체험하기 위해 다양한 활동에 참여했다. 동료들과의 대화에서 놓친 부분이 있으면 나중에 따로 물어보며 이해하려 노력했다. 이러한 그의 성실함과 열정은 동료들에게 좋은 인상을 주었다. 점차 시간이 지나면서 박민호는 미국 생활에 적응해갔다. 그의 영어 실력도 크게 향상되었고, 회사에서의 업무 능력도 인정받기 시작했다. 특히 그는 인공지능 연구 분야에서 두각을 나타냈다. 그가 개발한 알고리즘은 회사의 주요 프로젝트에 적용되어 큰 성과를 거두었다. 이러한 성과를 바탕으로 박민호는 실리콘밸리의 여러 대기업에서 스카우트 제의를 받았다. 그는 끊임없이 자신의 한계를 시험하며 새로운 기술을 배우고 연구했다.')

In [108]:
texts[6]

Document(metadata={}, page_content="그의 논문들이 주요 학회에서 발표되면서 학계에서도 그의 이름이 알려지기 시작했다. 2015년, 마침내 그는 세계적인 IT 기업인 구글에 합류하게 되었다. 이는 박민호에게 큰 전환점이 되었다. 구글에서 그는 다양한 인공지능 프로젝트에 참여하며, 글로벌 무대에서 자신의 역량을 발휘했다. 전 세계에서 모인 우수한 인재들과 협업하며 그는 더욱 성장할 수 있었다. 구글에서 박민호는 주로 자율주행 자동차 프로젝트와 관련된 인공지능 기술 개발에 깊이 관여했다. 그의 연구는 자율주행 시스템의 안전성과 효율성을 크게 향상시켰다. 이 업적으로 그는 회사 내에서 '올해의 혁신가' 상을 수상하기도 했다. 그러나 성공 속에서도 박민호는 고향과 가족에 대한 그리움을 잊지 않았다. 매년 휴가 때마다 한국을 방문해 어머니를 뵙고, 고향 마을을 찾아갔다. 그는 자신의 성공이 단지 개인의 노력만으로 이루어진 것이 아니라, 많은 이들의 지지와 격려 덕분이라고 생각했다. 한국에서의 재도전\n2020년, 박민호는 큰 결심을 하고 한국으로 돌아왔다. 그는 자신의 경험과 지식을 한국의 젊은 인재들과 나누고 싶다는 생각을 하게 되었다. 또한, 한국의 IT 산업이 글로벌 시장에서 더 큰 경쟁력을 갖출 수 있도록 돕고 싶었다. 귀국 후 그는 자신의 IT 스타트업을 설립했다. 회사의 이름은 '네오텍(NeoTech)'으로, '새로운 기술로 더 나은 미래를 만든다'는 의미를 담았다. 네오텍은 인공지능과 빅데이터 기술을 활용한 혁신적인 솔루션을 개발하는 것을 목표로 삼았다. 처음에는 많은 어려움이 있었다.")

# 백분위수 방식
유사도를 비교 하고 , 진짜 크게 바뀌는 지점을 자른다.
ex. 상위 5%

“얼마나 민감하게 자를지 결정하는 기준”


95 = 크게 바뀔 때만 자름


50 = 조금만 달라도 자름

In [110]:
# 의미 기준으로 텍스트를 나누는 청커 생성
# percentile=95 → 의미가 크게 바뀌는 상위 5% 지점에서만 자름 (덜 자름, 덩어리 큼)

text_splitter = SemanticChunker(
    OpenAIEmbeddings(),
    breakpoint_threshold_type="percentile",
    breakpoint_threshold_amount=95,
)

# 텍스트를 의미 단위로 분할
texts = text_splitter.create_documents([file])

# 분할된 청크 개수 출력
print("분할된 청크의 수:", len(texts))

분할된 청크의 수: 10

# 표준편차 방식
평균에서 얼마나 벗어났는지 , 벗어난 기준으로 자른다.


예시 ) 점수: 80, 82, 79, 81, 150 ---> 150 너무 멀리 떨어짐

청킹 적용시 예시

A: 오늘 날씨 좋다


B: 산책 나갔다


C: 기분 좋다


D: 주식 폭락했다  ← 갑자기 다른 주제

In [111]:
# 의미 기준으로 텍스트를 나누는 청커 생성
# standard_deviation=3 → 평균보다 3배 이상 크게 의미가 바뀌는 지점에서만 자름 (아주 덜 자름)

text_splitter = SemanticChunker(
    OpenAIEmbeddings(),
    breakpoint_threshold_type="standard_deviation",
    breakpoint_threshold_amount=3,
)

# 텍스트를 의미 단위로 분할
texts = text_splitter.create_documents([file])

# 분할된 청크 개수 출력
# standard_deviation=3 → 평균보다 3배 이상 차이날 때만 자름
print("분할된 청크의 수:", len(texts))

분할된 청크의 수: 3

# 사분위수 방식

갑자기 튀는 값 = 이상치


하위 25% | 중간 50% | 상위 25%


breakpoint_threshold_amount=1.5

일반 범위(중간 값들)에서 벗어나면 자름

In [113]:
# 의미 기준으로 텍스트를 나누는 청커 생성

text_splitter = SemanticChunker(
    OpenAIEmbeddings(),
    breakpoint_threshold_type="interquartile",
# interquartile=1.5 → 일반 범위를 벗어나는 지점(이상치)에서 자름
    breakpoint_threshold_amount=1.5,
)

# 텍스트를 의미 단위로 분할
texts = text_splitter.create_documents([file])

# 분할된 청크 개수 출력
print("분할된 청크의 수:", len(texts))

분할된 청크의 수: 7

# 옵션 정리

| 방식            | 기준        | 느낌     |
| ------------- | --------- | ------ |
| percentile    | 상위 %      | 비율 기준  |
| std           | 평균에서 튐    | 거리 기준  |
| interquartile | 일반 범위 벗어남 | 이상치 기준 |

# 랭체인을 이용 하여 GPT 호출

In [115]:
# LangChain에서 OpenAI 모델과 커뮤니티 기능을 사용하기 위한 패키지 설치
!pip install langchain_community langchain_openai

Requirement already satisfied: langchain_community in ./tf-env/lib/python3.12/site-packages (0.4.1)
Requirement already satisfied: langchain_openai in ./tf-env/lib/python3.12/site-packages (1.1.12)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (1.2.21)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (1.0.3)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (2.0.48)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (0.7.22)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in ./tf-env/lib/python3.12/site-packages (from langchain_community) (1.26.4)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in ./tf-env/lib/python3.12/site-packages (from langchain_openai) (2.29.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain_openai) (0.12.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./tf-env/lib/python3.12/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in ./tf-env/lib/python3.12/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.1 in ./tf-env/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (1.1.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./tf-env/lib/python3.12/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (1.33)
Requirement already satisfied: packaging>=23.2.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in ./tf-env/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (0.14.1)
Requirement already satisfied: httpx<1,>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in ./tf-env/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.25.0)
Requirement already satisfied: anyio<5,>=3.5.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (0.13.0)
Requirement already satisfied: sniffio in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (1.3.1)
Requirement already satisfied: tqdm>4 in ./tf-env/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (4.67.3)
Requirement already satisfied: python-dotenv>=0.21.0 in ./tf-env/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.2.2)
Requirement already satisfied: typing-inspection>=0.4.0 in ./tf-env/lib/python3.12/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./tf-env/lib/python3.12/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2026.2.25)
Requirement already satisfied: greenlet>=1 in ./tf-env/lib/python3.12/site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain_community) (3.3.2)
Requirement already satisfied: regex>=2022.1.18 in ./tf-env/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain_openai) (2026.2.28)
Requirement already satisfied: httpcore==1.* in ./tf-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./tf-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in ./tf-env/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain_community) (3.1.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./tf-env/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.41.5)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./tf-env/lib/python3.12/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain_community) (1.1.0)

In [116]:
import os  # 환경변수 설정 (API 키 등)

from langchain_openai import ChatOpenAI  # OpenAI GPT 모델 사용
from langchain_core.prompts import PromptTemplate  # 프롬프트 템플릿
from langchain_core.runnables.history import RunnableWithMessageHistory  # 대화 기록 유지
from langchain_community.chat_message_histories import ChatMessageHistory  # 메시지 저장 객체
from langchain_core.tracers.stdout import ConsoleCallbackHandler  # 실행 로그 출력

In [117]:
# OpenAI API 키 설정
os.environ["OPENAI_API_KEY"] = ""

# LLM(모델) 객체 생성
llm = ChatOpenAI(
    model_name="gpt-4o",   # 사용할 모델 이름
    temperature=0.1,       # 창의성 (낮을수록 정확, 높을수록 창의적)
    max_tokens=2048        # 최대 응답 길이
)

In [118]:
# 질의 내용 정의
question = "세종대왕이 누구인지 설명해주세요"

# 모델에 질문하고 결과 받기
result = llm.invoke(question)

# 결과 출력
print(result.content)

세종대왕은 조선의 제4대 왕으로, 본명은 이도입니다. 그는 1397년에 태어나 1418년부터 1450년까지 조선을 통치했습니다. 세종대왕은 한국 역사상 가장 존경받는 군주 중 한 명으로, 그의 통치 기간 동안 많은 문화적, 과학적 발전이 이루어졌습니다.

가장 유명한 업적 중 하나는 한글의 창제입니다. 세종대왕은 백성들이 쉽게 읽고 쓸 수 있는 문자를 만들고자 하여 1443년에 훈민정음을 창제하였고, 1446년에 반포하였습니다. 이는 오늘날 한국어의 문자 체계인 한글로 발전하였습니다.

또한, 세종대왕은 과학과 기술의 발전을 장려하였으며, 측우기와 해시계 같은 여러 과학 기구의 개발을 지원하였습니다. 그는 음악, 농업, 의학 등 다양한 분야에서도 혁신을 이루었으며, 백성을 위한 정책을 펼쳐 조선의 기틀을 다지는 데 큰 기여를 하였습니다.

In [120]:
# 질문 템플릿 정의 (변수 포함)
template = "{who}가 누구인지 설명해주세요"

# 템플릿 객체 생성
prompt = PromptTemplate(
    template=template,
    input_variables=["who"]  # 사용할 변수
)

# 템플릿 구조 확인 (미리보기)
print(prompt)

input_variables=['who'] input_types={} partial_variables={} template='{who}가 누구인지 설명해주세요'

In [121]:
# 템플릿에 값(who)을 넣어서 실제 문장 생성
print(prompt.format(who="오바마"))

오바마가 누구인지 설명해주세요

In [123]:
# 프롬프트와 LLM을 연결하여 체인 생성
llm_chain = prompt | llm

# 체인 실행 (변수 값 전달)
# invoke : 실행함수
result = llm_chain.invoke({"who": "이순신 장군"})

# 결과 출력
print(result.content)

이순신 장군은 조선 시대의 유명한 군인으로, 임진왜란(1592-1598) 동안 조선 해군을 이끌며 큰 공을 세운 인물입니다. 그는 1545년에 태어나 1598년에 전사하였습니다. 이순신은 특히 해전에서 뛰어난 전략과 전술을 발휘하여 일본군의 침략을 막아내는 데 중요한 역할을 했습니다.

그의 가장 유명한 업적 중 하나는 한산도 대첩으로, 이 전투에서 그는 학익진이라는 전술을 사용하여 일본 해군을 크게 무찌르는 데 성공했습니다. 또한, 명량 해전에서는 열세인 상황에서도 뛰어난 지휘력으로 승리를 거두었습니다.

이순신 장군은 그의 충성과 용맹함, 그리고 뛰어난 군사적 재능으로 인해 오늘날까지도 한국에서 존경받는 인물로 남아 있으며, 그의 삶과 업적은 많은 사람들에게 영감을 주고 있습니다.

In [124]:
# 체인 실행 + 실행 과정 로그 출력
result = llm_chain.invoke(
    {"who": "이순신 장군"},
    config={"callbacks": [ConsoleCallbackHandler()]}
)

[chain/start] [chain:RunnableSequence] Entering Chain run with input:
{
  "who": "이순신 장군"
}
[chain/start] [chain:RunnableSequence > prompt:PromptTemplate] Entering Prompt run with input:
{
  "who": "이순신 장군"
}
[chain/end] [chain:RunnableSequence > prompt:PromptTemplate] [0ms] Exiting Prompt run with output:
[outputs]
[llm/start] [chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: 이순신 장군가 누구인지 설명해주세요"
  ]
}
[llm/end] [chain:RunnableSequence > llm:ChatOpenAI] [4.60s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "이순신 장군은 조선 시대의 유명한 군인으로, 임진왜란 당시 조선 수군을 이끌어 일본군을 상대로 여러 차례 승리를 거둔 인물입니다. 그는 1545년 4월 28일에 태어나 1598년 12월 16일에 전사했습니다. 이순신은 특히 명량 해전과 한산도 대첩 등에서의 전략적 승리로 잘 알려져 있으며, 그의 뛰어난 해전 지휘 능력은 조선의 해상 방어에 큰 기여를 했습니다.\n\n이순신 장군은 거북선이라는 철갑선을 활용하여 일본군을 효과적으로 물리쳤고, 그의 전술과 리더십은 오늘날까지도 많은 사람들에게 존경받고 있습니다. 그는 충무공이라는 시호를 받았으며, 한국 역사에서 가장 위대한 군사 지도자 중 한 명으로 평가받고 있습니다. 그의 삶과 업적은 여러 문헌과 영화, 드라마 등을 통해 널리 알려져 있습니다.",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessage"
          ],
          "kwargs": {
            "content": "이순신 장군은 조선 시대의 유명한 군인으로, 임진왜란 당시 조선 수군을 이끌어 일본군을 상대로 여러 차례 승리를 거둔 인물입니다. 그는 1545년 4월 28일에 태어나 1598년 12월 16일에 전사했습니다. 이순신은 특히 명량 해전과 한산도 대첩 등에서의 전략적 승리로 잘 알려져 있으며, 그의 뛰어난 해전 지휘 능력은 조선의 해상 방어에 큰 기여를 했습니다.\n\n이순신 장군은 거북선이라는 철갑선을 활용하여 일본군을 효과적으로 물리쳤고, 그의 전술과 리더십은 오늘날까지도 많은 사람들에게 존경받고 있습니다. 그는 충무공이라는 시호를 받았으며, 한국 역사에서 가장 위대한 군사 지도자 중 한 명으로 평가받고 있습니다. 그의 삶과 업적은 여러 문헌과 영화, 드라마 등을 통해 널리 알려져 있습니다.",
            "additional_kwargs": {
              "refusal": null
            },
            "response_metadata": {
              "token_usage": {
                "completion_tokens": 229,
                "prompt_tokens": 17,
                "total_tokens": 246,
                "completion_tokens_details": {
                  "accepted_prediction_tokens": 0,
                  "audio_tokens": 0,
                  "reasoning_tokens": 0,
                  "rejected_prediction_tokens": 0
                },
                "prompt_tokens_details": {
                  "audio_tokens": 0,
                  "cached_tokens": 0
                }
              },
              "model_provider": "openai",
              "model_name": "gpt-4o-2024-08-06",
              "system_fingerprint": "fp_363ea47c38",
              "id": "chatcmpl-DMpNbJAKtwNPl9Wsdqr8AFyD4T4NH",
              "service_tier": "default",
              "finish_reason": "stop",
              "logprobs": null
            },
            "type": "ai",
            "id": "lc_run--019d1e7e-5995-74a0-83b1-61b90927ae2f-0",
            "usage_metadata": {
              "input_tokens": 17,
              "output_tokens": 229,
              "total_tokens": 246,
              "input_token_details": {
                "audio": 0,
                "cache_read": 0
              },
              "output_token_details": {
                "audio": 0,
                "reasoning": 0
              }
            },
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 229,
      "prompt_tokens": 17,
      "total_tokens": 246,
      "completion_tokens_details": {
        "accepted_prediction_tokens": 0,
        "audio_tokens": 0,
        "reasoning_tokens": 0,
        "rejected_prediction_tokens": 0
      },
      "prompt_tokens_details": {
        "audio_tokens": 0,
        "cached_tokens": 0
      }
    },
    "model_provider": "openai",
    "model_name": "gpt-4o-2024-08-06",
    "system_fingerprint": "fp_363ea47c38",
    "id": "chatcmpl-DMpNbJAKtwNPl9Wsdqr8AFyD4T4NH",
    "service_tier": "default"
  },
  "run": null,
  "type": "LLMResult"
}
[chain/end] [chain:RunnableSequence] [4.60s] Exiting Chain run with output:
[outputs]

내부에서 뭘 하는 지 볼수 있음.

흐름
1. 입력 들어옴
2. 프롬프트 생성
3. GPT 호출
4. 결과 반환


시작
[chain/start]

입력 (input)


"who": "이순신 장군"


프롬프트 생성 (템플릿 적용)


"이순신 장군가 누구인지 설명해주세요"

모델호출
[llm/start]

답변생성

종료
[chain/end]

In [133]:
# 프롬프트 템플릿 생성 (대화형 챗봇용)
# 이전 대화 + 현재 질문 → 프롬프트 생성 → GPT → 답변
# 대화 문맥 포함해서 답변하게 만드는 프롬프트

template = """아래는 사람과 AI의 친근한 대화입니다.
AI의 이름은 위키독스봇입니다.
이 AI는 위키독스에서 만들어졌습니다.
대화 문맥을 바탕으로 친절하게 답변하세요.

Current Conversation: {history}
Human: {input}
AI:"""

prompt = PromptTemplate(
    template=template,
    input_variables=["history", "input"]  # 이전 대화 + 현재 질문
)

# LLM 객체 생성
llm = ChatOpenAI(model_name="gpt-4o")

# 프롬프트와 LLM 연결 (체인 생성)
chain = prompt | llm

In [134]:
store = {}
session_id = "test"

In [135]:
# 아주 중요 : 사람 대화 섞일 수 있음 . 그러니 숙지할 것

# 사용자 세션이 없으면 새로 만들고 있으면 , 있으면 기존 대화 가져오기

# 해당 session_id가 없으면 새로운 대화 기록 생성
if session_id not in store:
    store[session_id] = ChatMessageHistory()

# 현재 세션의 대화 기록 가져오기
session_history = store[session_id]

In [136]:
# 체인에 대화 기록(메모리)을 연결
# 이전 대화(history) + 현재 질문(input)을 같이 넣어서 답변하도록 설정
with_message_history = RunnableWithMessageHistory(
    chain,
    lambda session_id: session_history,  # session_id에 해당하는 대화 기록 반환
    input_messages_key="input",          # 현재 사용자 입력 key
    history_messages_key="history"       # 이전 대화 기록 key
)

In [137]:
# 메모리를 포함한 체인 실행 (대화 유지됨)
result = with_message_history.invoke(
    {"input": "당신은 어디에서 만들어졌습니까?"},
    config={"configurable": {"session_id": "test"}}  # 사용자 구분 (세션)
)

# 결과 출력
print(result.content)

안녕하세요! 저는 위키독스에서 만들어졌어요. 위키독스는 교육과 학습을 위한 다양한 자료를 제공하는 플랫폼입니다. 궁금한 점이 있으면 언제든지 물어보세요!

안녕하세요! 저는 인터넷을 통해 유용하고 다양한 정보를 제공하기 위해 만들어졌습니다. 제 기반 기술은 여러 연구 기관과 기업에서 발전시킨 인공지능 기술입니다. 어떻게 도와드릴까요? <- 모르면 일반적인 대답을 하게 된다.

In [138]:
# 메모리를 유지하면서 새로운 질문 실행 (시 요청)
result = with_message_history.invoke(
    {"input": "푸른 바다를 주제로 감성적이고 짧은 시를 하나 지어주세요"},
    config={"configurable": {"session_id": "test"}}  # 같은 세션 → 이전 대화 유지
)

# 결과 출력
print(result.content)

푸른 바다의 속삭임,
끝없는 파도 위에 춤추는 빛,
바람에 실려 오는 바다의 향기,
내 마음 깊이 푸른 꿈을 그리네.

In [139]:
print(store)

{'test': InMemoryChatMessageHistory(messages=[HumanMessage(content='당신은 어디에서 만들어졌습니까?', additional_kwargs={}, response_metadata={}), AIMessage(content='안녕하세요! 저는 위키독스에서 만들어졌어요. 위키독스는 교육과 학습을 위한 다양한 자료를 제공하는 플랫폼입니다. 궁금한 점이 있으면 언제든지 물어보세요!', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 47, 'prompt_tokens': 76, 'total_tokens': 123, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_363ea47c38', 'id': 'chatcmpl-DMppevKvYxofZiafA458mmSCgdPSo', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019d1e98-e524-7da0-86b0-982f12bd73e8-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 76, 'output_tokens': 47, 'total_tokens': 123, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}), HumanMessage(content='푸른 바다를 주제로 감성적이고 짧은 시를 하나 지어주세요', additional_kwargs={}, response_metadata={}), AIMessage(content='푸른 바다의 속삭임,  \n끝없는 파도 위에 춤추는 빛,  \n바람에 실려 오는 바다의 향기,  \n내 마음 깊이 푸른 꿈을 그리네.  ', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 51, 'prompt_tokens': 438, 'total_tokens': 489, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_b558dd220d', 'id': 'chatcmpl-DMpqMVExkbRsHh0ZFBda16p8UQcMK', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019d1e99-90bd-7f31-8ccb-0ad87930aa58-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 438, 'output_tokens': 51, 'total_tokens': 489, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})])}


[대화 기록 저장 구조 설명]

- store 딕셔너리에 session_id를 key로 사용하여 대화 기록을 저장한다.
- 현재 예시에서는 "test"라는 session_id에 대한 대화가 저장되어 있다.

■ 구조
store = {
    "test": InMemoryChatMessageHistory(
        messages=[
            HumanMessage(content="사용자 질문"),
            AIMessage(content="AI 답변"),
            ...
        ]
    )
}

■ 구성 요소
- HumanMessage: 사용자의 입력 (질문)
- AIMessage: AI의 응답 (답변)

■ 동작 방식
1. 사용자가 질문을 입력하면 HumanMessage로 저장된다.
2. AI가 답변을 생성하면 AIMessage로 저장된다.
3. 이 메시지들이 순서대로 쌓이며 대화 기록(history)이 된다.
4. 이후 질문 시 이전 대화(history)가 함께 전달되어 문맥을 유지한다.

■ 핵심
- session_id 기준으로 사용자별 대화가 분리된다.
- 이 구조 덕분에 "이전 대화 기억하는 챗봇" 구현이 가능하다.